# chinese.py

TRANSLATIONS = {
    # 主对话框
    "Adicionar Cards com Delimitadores": "使用分隔符添加卡片",
    "Idioma:": "语言:",
    "Pronto": "就绪",
    "Cards: {}": "卡片: {}",
    "Adicionar Imagem, Som ou Vídeo": "添加图像、音频或视频",
    "Gerenciar Mídia": "管理媒体",
    "Exportar para HTML": "导出为HTML",
    "Exportar cards para arquivo HTML": "将卡片导出为HTML文件",
    "Visualizar Cards": "预览卡片",
    "Mostrar": "显示",
    "Mostra todos os cards do deck em 'Digite seus cards'": "在“输入卡片”中显示牌组中的所有卡片",
    "Editar": "编辑",
    "Parar Edição": "停止编辑",
    "Ativa/desativa a edição em tempo real dos cards mostrados.": "启用/禁用对已显示卡片的实时编辑。",
    "Digite seus cards:": "输入您的卡片:",
    "Aplicar cor ao texto": "应用文本颜色",
    "Aplicar cor de fundo ao texto": "应用背景颜色",
    "Digite seus cards aqui...": "在此处输入您的卡片...",
    "Etiquetas:": "标签:",
    "Digite as etiquetas aqui (uma linha por card)...": "在此处输入标签（每张卡片一行）...",
    "Preview:": "预览:",
    "Numerar Tags": "给标签编号",
    "Repetir Tags": "重复标签",
    "Mostrar Etiquetas": "显示标签",
    "Ocultar Etiquetas": "隐藏标签",
    "Mudar Tema": "更换主题",
    "Tema Claro": "浅色主题",
    "Tema Escuro": "深色主题",
    "📝 Editar em Grade": "📝 在表格中编辑",
    "📄 Editar como Texto": "📄 作为文本编辑",
    "Alterna entre a edição de texto livre e uma grade estilo planilha.": "在自由文本编辑和电子表格样式的表格之间切换。",
    "Juntar Linhas": "合并行",
    "Juntar todas as linhas": "合并所有行",
    "Destaque": "高亮",
    "Destacar texto (Ctrl+M)": "高亮文本 (Ctrl+M)",
    "B": "粗",
    "Negrito (Ctrl+B)": "粗体 (Ctrl+B)",
    "I": "斜",
    "Itálico (Ctrl+I)": "斜体 (Ctrl+I)",
    "U": "下",
    "Sublinhado (Ctrl+U)": "下划线 (Ctrl+U)",
    "Concatenar": "连接",
    "Concatenar texto": "连接文本",
    "Limpar Tudo": "全部清除",
    "Limpar todos os campos e configurações": "清除所有字段和设置",
    "Desfazer": "撤销",
    "Desfazer (Ctrl+Z)": "撤销 (Ctrl+Z)",
    "Refazer": "重做",
    "Refazer (Ctrl+Y)": "重做 (Ctrl+Y)",
    "Pesquisar... Ctrl+P": "搜索... Ctrl+P",
    "Pesquisar": "搜索",
    "Substituir tudo por... Ctrl+Shift+R": "全部替换为... Ctrl+Shift+R",
    "Substituir Tudo": "全部替换",
    "Cloze 1 (Ctrl+Shift+D)": "填空 1 (Ctrl+Shift+D)",
    "Adicionar Cloze 1 (Ctrl+Shift+D)": "添加填空 1 (Ctrl+Shift+D)",
    "Cloze 2 (Ctrl+Shift+F)": "填空 2 (Ctrl+Shift+F)",
    "Adicionar Cloze 2 (Ctrl+Shift+F)": "添加填空 2 (Ctrl+Shift+F)",
    "Remover Cloze": "移除填空",
    "Remover Cloze (sem atalho)": "移除填空 (无快捷键)",
    "Decks: {}": "牌组: {}",
    "Pesquisar decks...": "搜索牌组...",
    "Digite o nome do novo deck...": "输入新牌组的名称...",
    "Criar Deck": "创建牌组",
    "Excluir Deck": "删除牌组",
    "Modelos ou Tipos de Notas: {}": "笔记类型: {}",
    "Pesquisar tipos de notas...": "搜索笔记类型...",
    "Mapeamento de Campos": "字段映射",
    "Associe cada parte a um campo:": "将每个部分映射到一个字段:",
    "Parte {} -> Ignorar": "部分 {} -> 忽略",
    "Parte {} -> {}": "部分 {} -> {}",
    "Midia {}": "媒体 {}",
    "Delimitadores:": "分隔符:",
    "Tab": "制表符",
    "Vírgula": "逗号",
    "Ponto e Vírgula": "分号",
    "Dois Pontos": "冒号",
    "Interrogação": "问号",
    "Barra": "斜杠",
    "Exclamação": "感叹号",
    "Pipe": "管道符 (|)",
    "Ocultar Decks/Modelos/Delimitadores": "隐藏牌组/模板/分隔符",
    "Mostrar Decks/Modelos/Delimitadores": "显示牌组/模板/分隔符",
    "Adicionar Cards (Ctrl+R)": "添加卡片 (Ctrl+R)",
    "Salvando...": "正在保存...",
    "Salvo": "已保存",
    "Erro ao salvar": "保存时出错",
    "Selecione um modelo para ver a pré-visualização.": "请选择一个笔记类型以进行预览。",
    "Erro:": "错误:",
    "Modelo não encontrado.": "未找到笔记类型。",
    "Frente do Cartão (Preview)": "卡片正面 (预览)",
    "Verso do Cartão (Preview)": "卡片背面 (预览)",
    "Erro na pré-visualização:": "预览时出错:",
    "Confirmação": "确认",
    "Tem certeza de que deseja limpar tudo? Isso não pode ser desfeito.": "您确定要清除所有内容吗？此操作无法撤销。",
    "Todos os campos e configurações foram limpos!": "所有字段和设置均已清除！",
    "Selecione um deck e um modelo!": "请选择一个牌组和笔记类型！",
    "Digite algum conteúdo!": "请输入一些内容！",
    "{} cards adicionados com sucesso!": "成功添加了 {} 张卡片！",
    "Selecione um deck primeiro!": "请先选择一个牌组！",
    "Deck '{}' não encontrado!": "未找到牌组 '{}'！",
    "Nenhum card encontrado no deck '{}'!": "在牌组 '{}' 中未找到任何卡片！",
    "Erro ao salvar estado antes de 'Mostrar': {}": "在“显示”前保存状态时出错: {}",
    "Use a função 'Mostrar' para carregar os cards de um deck antes de editar.": "在编辑前，请使用“显示”功能从牌组加载卡片。",
    "Modo de edição ativado.": "编辑模式已启用。",
    "Modo de edição desativado.": "编辑模式已禁用。",
    "O número de linhas foi alterado. Modo de edição desativado para evitar erros.": "行数已更改。为避免错误，编辑模式已禁用。",
    "Atualizando card...": "正在更新卡片...",
    "Card {} atualizado!": "卡片 {} 已更新！",
    "Erro ao atualizar": "更新时出错",
    "Nenhum estado anterior salvo encontrado!": "未找到先前保存的状态。",
    "Por favor, selecione uma célula na grade primeiro.": "请先在表格中选择一个单元格。",
    "Selecionar Mídia": "选择媒体",
    "🖼️ Adicionar Imagem/Mídia...": "🖼️ 添加图像/媒体...",
    "Colar HTML sem Tag e sem Formatação": "粘贴无标签和格式的HTML",
    "Colar com Tags HTML": "带HTML标签粘贴",
    "Colar do Excel com Ponto e Vírgula": "从Excel粘贴（带分号）",
    "Colar do Word": "从Word粘贴",
    "Nenhuma imagem, texto ou HTML encontrado na área de transferência.": "剪贴板中未找到图像、文本或HTML。",
    "Nenhum texto encontrado na área de transferência para colar como Excel.": "剪贴板中未找到可作为Excel粘贴的文本。",
    "Nenhum texto encontrado na área de transferência para colar como Word.": "剪贴板中未找到可作为Word粘贴的文本。",
    "Nenhum texto ou HTML encontrado na área de transferência.": "剪贴板中未找到文本或HTML。",
    "Erro na Exportação": "导出错误",
    "Ocorreu um erro durante a exportação: {}": "导出时发生错误: {}",
    "Por favor, insira um texto para pesquisar.": "请输入要搜索的文本。",
    "Texto '{}' não encontrado.": "未找到文本 '{}'。",
    "Todas as ocorrências de '{}' foram substituídas por '{}'.": "'{}' 的所有实例已被 '{}' 替换。",
    "Todas as ocorrências de '{}' foram removidas.": "'{}' 的所有实例已被移除。",
    "Por favor, insira um nome para o deck!": "请输入牌组名称！",
    "Erro ao criar o deck: {}": "创建牌组时出错: {}",
    "Etiquetas (Selecionado)": "标签 (已选择)",
    "Por favor, selecione uma palavra para adicionar o cloze.": "请选择一个词来添加填空。",
    "Erro ao carregar configurações: {}": "加载设置时出错: {}",
    "Nenhum arquivo de mídia foi adicionado ou referenciado no texto!": "文本中没有添加或引用任何媒体文件！",
    "Selecionar Mídia para {}": "为 {} 选择媒体",
    "Ocultar Ferramentas": "隐藏工具",
    "Mostrar Ferramentas": "显示工具",
    "Campo {}": "字段 {}",
    "Confirmar Exclusão de Deck": "确认删除牌组",
    "Você tem certeza que deseja excluir o deck '{}'?\n\nIsso excluirá permanentemente {} card(s) e suas mídias associadas (se não forem usadas em outros decks).\n\nESTA AÇÃO NÃO PODE SER DESFEITA.": "您确定要删除牌组 '{}' 吗？\n\n这将永久删除 {} 张卡片及其相关媒体（如果未被其他牌组使用）。\n\n此操作无法撤销。",
    "Ocorreu um erro ao excluir o deck: {}": "删除牌组时发生错误: {}",

    # 排序按钮
    "Ordem Alfabética": "按字母顺序",
    "Organizar cards em ordem alfabética (A-Z / Z-A)": "按字母顺序排列卡片 (A-Z / Z-A)",
    "Ordem de Criação": "按创建顺序",
    "Organizar por data de criação e mostrar/ocultar data": "按创建日期排序并显示/隐藏日期",
    "Ordem Aleatória": "随机顺序",
    "Organizar cards em ordem aleatória": "随机排列卡片",
    "Mais Errados": "错误最多",
    "Organizar por cards mais errados (com mais lapsos)": "按错误最多的卡片排序（失误更多）",
    "Mais Certos": "错误最少",
    "Organizar por cards mais certos (com menos lapsos)": "按错误最少的卡片排序（失误更少）",

    # 媒体管理器
    "Gerenciador de Mídia": "媒体管理器",
    "Arquivos de Mídia Atuais": "当前媒体文件",
    "Renomear": "重命名",
    "Deletar": "删除",
    "Deletar Todos": "全部删除",
    "Preview da Mídia": "媒体预览",
    "Renomear Arquivo": "重命名文件",
    "Novo nome:": "新名称:",
    "Confirmar Exclusão": "确认删除",
    "Tem certeza de que deseja deletar o arquivo '{}'?": "您确定要删除文件 '{}' 吗？",
    "Tem certeza de que deseja deletar TODOS os {} arquivos de mídia?": "您确定要删除所有 {} 个媒体文件吗？",
    "Arquivo renomeado de '{}' para '{}'.": "文件已从 '{}' 重命名为 '{}'。",
    "O nome '{}' já existe. Por favor, escolha outro nome.": "名称 '{}' 已存在。请选择其他名称。",
    "Erro ao renomear arquivo: {}": "重命名文件时出错: {}",
    "Arquivo '{}' deletado com sucesso.": "文件 '{}' 已成功删除。",
    "Erro ao deletar arquivo: {}": "删除文件时出错: {}",
    "Todos os arquivos de mídia foram deletados.": "所有媒体文件均已删除。",
    "Nenhum arquivo de mídia para deletar.": "没有要删除的媒体文件。",

    # 卡片查看器
    "Visualizador de Cards": "卡片查看器",
    "Gerar": "生成",
    "Copiar para Área de Transferência": "复制到剪贴板",
    "Salvar como HTML": "另存为HTML",
    "Impressão": "打印",
    "Nenhum card para visualizar.": "没有可供查看的卡片。",
    "Conteúdo copiado para a área de transferência!": "内容已复制到剪贴板！",
    "Salvar Arquivo HTML": "保存HTML文件",
    "Arquivo HTML salvo em: {}": "HTML文件已保存至: {}",
    "Erro ao salvar arquivo: {}": "保存文件时出错: {}",
    "Visualização de Impressão": "打印预览",
    "Erro ao gerar preview de impressão: {}": "生成打印预览时出错: {}",

    # 新手模式
    "Modo Iniciante": "新手模式",
    "Modo Completo": "完整模式",
    "Simplifica a interface para mostrar apenas as funções essenciais.": "简化界面以仅显示基本功能。",
    "Mostra todas as ferramentas avançadas.": "显示所有高级工具。",
    "instructions_button": "说明",
    "instructions_title": "说明 (新手模式)",
    "beginner_instructions_line1": "<b>1. 每行一张卡片。</b>",
    "beginner_instructions_line2": "<b>2. 使用分号 ( ; ) 分隔正面和背面。</b>",
    "beginner_instructions_example_title": "例如:",
    "beginner_instructions_example_text": "中国首都 ; 北京",
}