# english.py

TRANSLATIONS = {
    # Main Dialog
    "Adicionar Cards com Delimitadores": "Add Cards with Delimiters",
    "Idioma:": "Language:",
    "Pronto": "Ready",
    "Cards: {}": "Cards: {}",
    "Adicionar Imagem, Som ou Vídeo": "Add Image, Sound, or Video",
    "Gerenciar Mídia": "Manage Media",
    "Exportar para HTML": "Export to HTML",
    "Exportar cards para arquivo HTML": "Export cards to an HTML file",
    "Visualizar Cards": "View Cards",
    "Mostrar": "Show",
    "Mostra todos os cards do deck em 'Digite seus cards'": "Shows all cards from the deck in 'Enter your cards'",
    "Editar": "Edit",
    "Parar Edição": "Stop Editing",
    "Ativa/desativa a edição em tempo real dos cards mostrados.": "Enables/disables real-time editing of the shown cards.",
    "Digite seus cards:": "Enter your cards:",
    "Aplicar cor ao texto": "Apply color to text",
    "Aplicar cor de fundo ao texto": "Apply background color to text",
    "Digite seus cards aqui...": "Enter your cards here...",
    "Etiquetas:": "Tags:",
    "Digite as etiquetas aqui (uma linha por card)...": "Enter tags here (one line per card)...",
    "Preview:": "Preview:",
    "Numerar Tags": "Number Tags",
    "Repetir Tags": "Repeat Tags",
    "Mostrar Etiquetas": "Show Tags",
    "Ocultar Etiquetas": "Hide Tags",
    "Mudar Tema": "Change Theme",
    "Tema Claro": "Light Theme",
    "Tema Escuro": "Dark Theme",
    "📝 Editar em Grade": "📝 Edit in Grid",
    "📄 Editar como Texto": "📄 Edit as Text",
    "Alterna entre a edição de texto livre e uma grade estilo planilha.": "Toggles between free text editing and a spreadsheet-style grid.",
    "Juntar Linhas": "Join Lines",
    "Juntar todas as linhas": "Join all lines",
    "Destaque": "Highlight",
    "Destacar texto (Ctrl+M)": "Highlight text (Ctrl+M)",
    "B": "B",
    "Negrito (Ctrl+B)": "Bold (Ctrl+B)",
    "I": "I",
    "Itálico (Ctrl+I)": "Italic (Ctrl+I)",
    "U": "U",
    "Sublinhado (Ctrl+U)": "Underline (Ctrl+U)",
    "Concatenar": "Concatenate",
    "Concatenar texto": "Concatenate text",
    "Limpar Tudo": "Clear All",
    "Limpar todos os campos e configurações": "Clear all fields and settings",
    "Desfazer": "Undo",
    "Desfazer (Ctrl+Z)": "Undo (Ctrl+Z)",
    "Refazer": "Redo",
    "Refazer (Ctrl+Y)": "Redo (Ctrl+Y)",
    "Pesquisar... Ctrl+P": "Search... Ctrl+P",
    "Pesquisar": "Search",
    "Substituir tudo por... Ctrl+Shift+R": "Replace all with... Ctrl+Shift+R",
    "Substituir Tudo": "Replace All",
    "Cloze 1 (Ctrl+Shift+D)": "Cloze 1 (Ctrl+Shift+D)",
    "Adicionar Cloze 1 (Ctrl+Shift+D)": "Add Cloze 1 (Ctrl+Shift+D)",
    "Cloze 2 (Ctrl+Shift+F)": "Cloze 2 (Ctrl+Shift+F)",
    "Adicionar Cloze 2 (Ctrl+Shift+F)": "Add Cloze 2 (Ctrl+Shift+F)",
    "Remover Cloze": "Remove Cloze",
    "Remover Cloze (sem atalho)": "Remove Cloze (no shortcut)",
    "Decks: {}": "Decks: {}",
    "Pesquisar decks...": "Search decks...",
    "Digite o nome do novo deck...": "Enter the new deck name...",
    "Criar Deck": "Create Deck",
    "Excluir Deck": "Delete Deck",
    "Modelos ou Tipos de Notas: {}": "Note Types: {}",
    "Pesquisar tipos de notas...": "Search note types...",
    "Mapeamento de Campos": "Field Mapping",
    "Associe cada parte a um campo:": "Map each part to a field:",
    "Parte {} -> Ignorar": "Part {} -> Ignore",
    "Parte {} -> {}": "Part {} -> {}",
    "Midia {}": "Media {}",
    "Delimitadores:": "Delimiters:",
    "Tab": "Tab",
    "Vírgula": "Comma",
    "Ponto e Vírgula": "Semicolon",
    "Dois Pontos": "Colon",
    "Interrogação": "Question Mark",
    "Barra": "Slash",
    "Exclamação": "Exclamation Mark",
    "Pipe": "Pipe",
    "Ocultar Decks/Modelos/Delimitadores": "Hide Decks/Models/Delimiters",
    "Mostrar Decks/Modelos/Delimitadores": "Show Decks/Models/Delimiters",
    "Adicionar Cards (Ctrl+R)": "Add Cards (Ctrl+R)",
    "Salvando...": "Saving...",
    "Salvo": "Saved",
    "Erro ao salvar": "Error saving",
    "Selecione um modelo para ver a pré-visualização.": "Select a note type to see the preview.",
    "Erro:": "Error:",
    "Modelo não encontrado.": "Note type not found.",
    "Frente do Cartão (Preview)": "Card Front (Preview)",
    "Verso do Cartão (Preview)": "Card Back (Preview)",
    "Erro na pré-visualização:": "Preview error:",
    "Confirmação": "Confirmation",
    "Tem certeza de que deseja limpar tudo? Isso não pode ser desfeito.": "Are you sure you want to clear everything? This cannot be undone.",
    "Todos os campos e configurações foram limpos!": "All fields and settings have been cleared!",
    "Selecione um deck e um modelo!": "Select a deck and a note type!",
    "Digite algum conteúdo!": "Enter some content!",
    "{} cards adicionados com sucesso!": "{} cards added successfully!",
    "Selecione um deck primeiro!": "Select a deck first!",
    "Deck '{}' não encontrado!": "Deck '{}' not found!",
    "Nenhum card encontrado no deck '{}'!": "No cards found in deck '{}'!",
    "Erro ao salvar estado antes de 'Mostrar': {}": "Error saving state before 'Show': {}",
    "Use a função 'Mostrar' para carregar os cards de um deck antes de editar.": "Use the 'Show' function to load cards from a deck before editing.",
    "Modo de edição ativado.": "Edit mode enabled.",
    "Modo de edição desativado.": "Edit mode disabled.",
    "O número de linhas foi alterado. Modo de edição desativado para evitar erros.": "The number of lines has changed. Edit mode disabled to prevent errors.",
    "Atualizando card...": "Updating card...",
    "Card {} atualizado!": "Card {} updated!",
    "Erro ao atualizar": "Error updating",
    "Nenhum estado anterior salvo encontrado!": "No previous saved state found!",
    "Por favor, selecione uma célula na grade primeiro.": "Please select a cell in the grid first.",
    "Selecionar Mídia": "Select Media",
    "🖼️ Adicionar Imagem/Mídia...": "🖼️ Add Image/Media...",
    "Colar HTML sem Tag e sem Formatação": "Paste HTML without Tags and Formatting",
    "Colar com Tags HTML": "Paste with HTML Tags",
    "Colar do Excel com Ponto e Vírgula": "Paste from Excel with Semicolon",
    "Colar do Word": "Paste from Word",
    "Nenhuma imagem, texto ou HTML encontrado na área de transferência.": "No image, text, or HTML found on the clipboard.",
    "Nenhum texto encontrado na área de transferência para colar como Excel.": "No text found on the clipboard to paste as Excel.",
    "Nenhum texto encontrado na área de transferência para colar como Word.": "No text found on the clipboard to paste as Word.",
    "Nenhum texto ou HTML encontrado na área de transferência.": "No text or HTML found on the clipboard.",
    "Erro na Exportação": "Export Error",
    "Ocorreu um erro durante a exportação: {}": "An error occurred during export: {}",
    "Por favor, insira um texto para pesquisar.": "Please enter text to search.",
    "Texto '{}' não encontrado.": "Text '{}' not found.",
    "Todas as ocorrências de '{}' foram substituídas por '{}'.": "All occurrences of '{}' were replaced with '{}'.",
    "Todas as ocorrências de '{}' foram removidas.": "All occurrences of '{}' were removed.",
    "Por favor, insira um nome para o deck!": "Please enter a name for the deck!",
    "Erro ao criar o deck: {}": "Error creating deck: {}",
    "Etiquetas (Selecionado)": "Tags (Selected)",
    "Por favor, selecione uma palavra para adicionar o cloze.": "Please select a word to add the cloze.",
    "Erro ao carregar configurações: {}": "Error loading settings: {}",
    "Nenhum arquivo de mídia foi adicionado ou referenciado no texto!": "No media files have been added or referenced in the text!",
    "Selecionar Mídia para {}": "Select Media for {}",
    "Ocultar Ferramentas": "Hide Tools",
    "Mostrar Ferramentas": "Show Tools",
    "Campo {}": "Field {}",
    "Confirmar Exclusão de Deck": "Confirm Deck Deletion",
    "Você tem certeza que deseja excluir o deck '{}'?\n\nIsso excluirá permanentemente {} card(s) e suas mídias associadas (se não forem usadas em outros decks).\n\nESTA AÇÃO NÃO PODE SER DESFEITA.": "Are you sure you want to delete the deck '{}'?\n\nThis will permanently delete {} card(s) and their associated media (if not used by other decks).\n\nTHIS ACTION CANNOT BE UNDONE.",
    "Ocorreu um erro ao excluir o deck: {}": "An error occurred while deleting the deck: {}",

    # New sorting buttons
    "Ordem Alfabética": "Alphabetical Order",
    "Organizar cards em ordem alfabética (A-Z / Z-A)": "Sort cards in alphabetical order (A-Z / Z-A)",
    "Ordem de Criação": "Creation Order",
    "Organizar por data de criação e mostrar/ocultar data": "Sort by creation date and show/hide date",
    "Ordem Aleatória": "Random Order",
    "Organizar cards em ordem aleatória": "Sort cards in random order",
    "Mais Errados": "Most Lapses",
    "Organizar por cards mais errados (com mais lapsos)": "Sort by most failed cards (with more lapses)",
    "Mais Certos": "Fewest Lapses",
    "Organizar por cards mais certos (com menos lapsos)": "Sort by most correct cards (with fewer lapses)",

    # Media Manager Dialog
    "Gerenciador de Mídia": "Media Manager",
    "Arquivos de Mídia Atuais": "Current Media Files",
    "Renomear": "Rename",
    "Deletar": "Delete",
    "Deletar Todos": "Delete All",
    "Preview da Mídia": "Media Preview",
    "Renomear Arquivo": "Rename File",
    "Novo nome:": "New name:",
    "Confirmar Exclusão": "Confirm Deletion",
    "Tem certeza de que deseja deletar o arquivo '{}'?": "Are you sure you want to delete the file '{}'?",
    "Tem certeza de que deseja deletar TODOS os {} arquivos de mídia?": "Are you sure you want to delete ALL {} media files?",
    "Arquivo renomeado de '{}' para '{}'.": "File renamed from '{}' to '{}'.",
    "O nome '{}' já existe. Por favor, escolha outro nome.": "The name '{}' already exists. Please choose another name.",
    "Erro ao renomear arquivo: {}": "Error renaming file: {}",
    "Arquivo '{}' deletado com sucesso.": "File '{}' deleted successfully.",
    "Erro ao deletar arquivo: {}": "Error deleting file: {}",
    "Todos os arquivos de mídia foram deletados.": "All media files have been deleted.",
    "Nenhum arquivo de mídia para deletar.": "No media files to delete.",

    # Card Viewer Dialog
    "Visualizador de Cards": "Card Viewer",
    "Gerar": "Generate",
    "Copiar para Área de Transferência": "Copy to Clipboard",
    "Salvar como HTML": "Save as HTML",
    "Impressão": "Print",
    "Nenhum card para visualizar.": "No cards to view.",
    "Conteúdo copiado para a área de transferência!": "Content copied to clipboard!",
    "Salvar Arquivo HTML": "Save HTML File",
    "Arquivo HTML salvo em: {}": "HTML file saved at: {}",
    "Erro ao salvar arquivo: {}": "Error saving file: {}",
    "Visualização de Impressão": "Print Preview",
    "Erro ao gerar preview de impressão: {}": "Error generating print preview: {}",


    "Modo Iniciante": "Beginner Mode",
    "Modo Completo": "Full Mode",
    "Simplifica a interface para mostrar apenas as funções essenciais.": "Simplifies the interface to show only essential functions.",
    "Mostra todas as ferramentas avançadas.": "Shows all advanced tools.",

    "instructions_button": "Instructions",
    "instructions_title": "Instructions (Beginner Mode)",
    "beginner_instructions_line1": "<b>1. One card per line.</b>",
    "beginner_instructions_line2": "<b>2. Separate the front from the back with a semicolon ( ; ).</b>",
    "beginner_instructions_example_title": "Example:",
    "beginner_instructions_example_text": "capital of the USA; Washington",


}