# french.py

TRANSLATIONS = {
    # Dialogue Principal
    "Adicionar Cards com Delimitadores": "Ajouter des Cartes avec Délimiteurs",
    "Idioma:": "Langue :",
    "Pronto": "Prêt",
    "Cards: {}": "Cartes : {}",
    "Adicionar Imagem, Som ou Vídeo": "Ajouter Image, Son ou Vidéo",
    "Gerenciar Mídia": "Gérer les Médias",
    "Exportar para HTML": "Exporter en HTML",
    "Exportar cards para arquivo HTML": "Exporter les cartes vers un fichier HTML",
    "Visualizar Cards": "Visualiser les Cartes",
    "Mostrar": "Afficher",
    "Mostra todos os cards do deck em 'Digite seus cards'": "Affiche toutes les cartes du paquet dans 'Entrez vos cartes'",
    "Editar": "Modifier",
    "Parar Edição": "Arrêter la Modification",
    "Ativa/desativa a edição em tempo real dos cards mostrados.": "Active/désactive l'édition en temps réel des cartes affichées.",
    "Digite seus cards:": "Entrez vos cartes :",
    "Aplicar cor ao texto": "Appliquer une couleur au texte",
    "Aplicar cor de fundo ao texto": "Appliquer une couleur de fond au texte",
    "Digite seus cards aqui...": "Entrez vos cartes ici...",
    "Etiquetas:": "Étiquettes :",
    "Digite as etiquetas aqui (uma linha por card)...": "Entrez les étiquettes ici (une ligne par carte)...",
    "Preview:": "Aperçu :",
    "Numerar Tags": "Numéroter les Étiquettes",
    "Repetir Tags": "Répéter les Étiquettes",
    "Mostrar Etiquetas": "Afficher les Étiquettes",
    "Ocultar Etiquetas": "Masquer les Étiquettes",
    "Mudar Tema": "Changer de Thème",
    "Tema Claro": "Thème Clair",
    "Tema Escuro": "Thème Sombre",
    "📝 Editar em Grade": "📝 Modifier en Grille",
    "📄 Editar como Texto": "📄 Modifier en Texte",
    "Alterna entre a edição de texto livre e uma grade estilo planilha.": "Bascule entre l'édition de texte libre et une grille de type tableur.",
    "Juntar Linhas": "Joindre les Lignes",
    "Juntar todas as linhas": "Joindre toutes les lignes",
    "Destaque": "Surligner",
    "Destacar texto (Ctrl+M)": "Surligner le texte (Ctrl+M)",
    "B": "G",
    "Negrito (Ctrl+B)": "Gras (Ctrl+B)",
    "I": "I",
    "Itálico (Ctrl+I)": "Italique (Ctrl+I)",
    "U": "S",
    "Sublinhado (Ctrl+U)": "Souligné (Ctrl+U)",
    "Concatenar": "Concaténer",
    "Concatenar texto": "Concaténer le texte",
    "Limpar Tudo": "Tout Effacer",
    "Limpar todos os campos e configurações": "Effacer tous les champs et paramètres",
    "Desfazer": "Annuler",
    "Desfazer (Ctrl+Z)": "Annuler (Ctrl+Z)",
    "Refazer": "Rétablir",
    "Refazer (Ctrl+Y)": "Rétablir (Ctrl+Y)",
    "Pesquisar... Ctrl+P": "Rechercher... Ctrl+P",
    "Pesquisar": "Rechercher",
    "Substituir tudo por... Ctrl+Shift+R": "Remplacer tout par... Ctrl+Shift+R",
    "Substituir Tudo": "Tout Remplacer",
    "Cloze 1 (Ctrl+Shift+D)": "Cloze 1 (Ctrl+Shift+D)",
    "Adicionar Cloze 1 (Ctrl+Shift+D)": "Ajouter Cloze 1 (Ctrl+Shift+D)",
    "Cloze 2 (Ctrl+Shift+F)": "Cloze 2 (Ctrl+Shift+F)",
    "Adicionar Cloze 2 (Ctrl+Shift+F)": "Ajouter Cloze 2 (Ctrl+Shift+F)",
    "Remover Cloze": "Supprimer Cloze",
    "Remover Cloze (sem atalho)": "Supprimer Cloze (sans raccourci)",
    "Decks: {}": "Paquets : {}",
    "Pesquisar decks...": "Rechercher des paquets...",
    "Digite o nome do novo deck...": "Entrez le nom du nouveau paquet...",
    "Criar Deck": "Créer Paquet",
    "Excluir Deck": "Supprimer Paquet",
    "Modelos ou Tipos de Notas: {}": "Types de Note : {}",
    "Pesquisar tipos de notas...": "Rechercher des types de note...",
    "Mapeamento de Campos": "Mappage des Champs",
    "Associe cada parte a um campo:": "Associez chaque partie à un champ :",
    "Parte {} -> Ignorar": "Partie {} -> Ignorer",
    "Parte {} -> {}": "Partie {} -> {}",
    "Midia {}": "Média {}",
    "Delimitadores:": "Délimiteurs :",
    "Tab": "Tabulation",
    "Vírgula": "Virgule",
    "Ponto e Vírgula": "Point-virgule",
    "Dois Pontos": "Deux-points",
    "Interrogação": "Point d'interrogation",
    "Barra": "Barre oblique",
    "Exclamação": "Point d'exclamation",
    "Pipe": "Pipe (|)",
    "Ocultar Decks/Modelos/Delimitadores": "Masquer Paquets/Modèles/Délimiteurs",
    "Mostrar Decks/Modelos/Delimitadores": "Afficher Paquets/Modèles/Délimiteurs",
    "Adicionar Cards (Ctrl+R)": "Ajouter des Cartes (Ctrl+R)",
    "Salvando...": "Enregistrement...",
    "Salvo": "Enregistré",
    "Erro ao salvar": "Erreur d'enregistrement",
    "Selecione um modelo para ver a pré-visualização.": "Sélectionnez un type de note pour voir l'aperçu.",
    "Erro:": "Erreur :",
    "Modelo não encontrado.": "Type de note non trouvé.",
    "Frente do Cartão (Preview)": "Recto de la Carte (Aperçu)",
    "Verso do Cartão (Preview)": "Verso de la Carte (Aperçu)",
    "Erro na pré-visualização:": "Erreur d'aperçu :",
    "Confirmação": "Confirmation",
    "Tem certeza de que deseja limpar tudo? Isso não pode ser desfeito.": "Êtes-vous sûr de vouloir tout effacer ? Cette action est irréversible.",
    "Todos os campos e configurações foram limpos!": "Tous les champs et paramètres ont été effacés !",
    "Selecione um deck e um modelo!": "Sélectionnez un paquet et un type de note !",
    "Digite algum conteúdo!": "Entrez du contenu !",
    "{} cards adicionados com sucesso!": "{} cartes ajoutées avec succès !",
    "Selecione um deck primeiro!": "Sélectionnez d'abord un paquet !",
    "Deck '{}' não encontrado!": "Paquet '{}' non trouvé !",
    "Nenhum card encontrado no deck '{}'!": "Aucune carte trouvée dans le paquet '{}' !",
    "Erro ao salvar estado antes de 'Mostrar': {}": "Erreur lors de la sauvegarde de l'état avant 'Afficher' : {}",
    "Use a função 'Mostrar' para carregar os cards de um deck antes de editar.": "Utilisez la fonction 'Afficher' pour charger les cartes d'un paquet avant de les modifier.",
    "Modo de edição ativado.": "Mode édition activé.",
    "Modo de edição desativado.": "Mode édition désactivé.",
    "O número de linhas foi alterado. Modo de edição desativado para evitar erros.": "Le nombre de lignes a changé. Mode édition désactivé pour éviter les erreurs.",
    "Atualizando card...": "Mise à jour de la carte...",
    "Card {} atualizado!": "Carte {} mise à jour !",
    "Erro ao atualizar": "Erreur de mise à jour",
    "Nenhum estado anterior salvo encontrado!": "Aucun état précédent enregistré n'a été trouvé.",
    "Por favor, selecione uma célula na grade primeiro.": "Veuillez d'abord sélectionner une cellule dans la grille.",
    "Selecionar Mídia": "Sélectionner un Média",
    "🖼️ Adicionar Imagem/Mídia...": "🖼️ Ajouter Image/Média...",
    "Colar HTML sem Tag e sem Formatação": "Coller HTML sans Balises ni Formatage",
    "Colar com Tags HTML": "Coller avec les Balises HTML",
    "Colar do Excel com Ponto e Vírgula": "Coller depuis Excel avec Point-Virgule",
    "Colar do Word": "Coller depuis Word",
    "Nenhuma imagem, texto ou HTML encontrado na área de transferência.": "Aucune image, texte ou HTML trouvé dans le presse-papiers.",
    "Nenhum texto encontrado na área de transferência para colar como Excel.": "Aucun texte trouvé dans le presse-papiers à coller depuis Excel.",
    "Nenhum texto encontrado na área de transferência para colar como Word.": "Aucun texte trouvé dans le presse-papiers à coller depuis Word.",
    "Nenhum texto ou HTML encontrado na área de transferência.": "Aucun texte ou HTML trouvé dans le presse-papiers.",
    "Erro na Exportação": "Erreur d'Exportation",
    "Ocorreu um erro durante a exportação: {}": "Une erreur est survenue lors de l'exportation : {}",
    "Por favor, insira um texto para pesquisar.": "Veuillez entrer un texte à rechercher.",
    "Texto '{}' não encontrado.": "Texte '{}' non trouvé.",
    "Todas as ocorrências de '{}' foram substituídas por '{}'.": "Toutes les occurrences de '{}' ont été remplacées par '{}'.",
    "Todas as ocorrências de '{}' foram removidas.": "Toutes les occurrences de '{}' ont été supprimées.",
    "Por favor, insira um nome para o deck!": "Veuillez entrer un nom pour le paquet !",
    "Erro ao criar o deck: {}": "Erreur lors de la création du paquet : {}",
    "Etiquetas (Selecionado)": "Étiquettes (Sélectionné)",
    "Por favor, selecione uma palavra para adicionar o cloze.": "Veuillez sélectionner un mot pour ajouter le cloze.",
    "Erro ao carregar configurações: {}": "Erreur lors du chargement des paramètres : {}",
    "Nenhum arquivo de mídia foi adicionado ou referenciado no texto!": "Aucun fichier multimédia n'a été ajouté ou référencé dans le texte !",
    "Selecionar Mídia para {}": "Sélectionner un Média pour {}",
    "Ocultar Ferramentas": "Masquer les Outils",
    "Mostrar Ferramentas": "Afficher les Outils",
    "Campo {}": "Champ {}",
    "Confirmar Exclusão de Deck": "Confirmer la Suppression du Paquet",
    "Você tem certeza que deseja excluir o deck '{}'?\n\nIsso excluirá permanentemente {} card(s) e suas mídias associadas (se não forem usadas em outros decks).\n\nESTA AÇÃO NÃO PODE SER DESFEITA.": "Êtes-vous sûr de vouloir supprimer le paquet '{}' ?\n\nCela supprimera définitivement {} carte(s) et leurs médias associés (s'ils ne sont pas utilisés par d'autres paquets).\n\nCETTE ACTION EST IRRÉVERSIBLE.",
    "Ocorreu um erro ao excluir o deck: {}": "Une erreur est survenue lors de la suppression du paquet : {}",

    # Boutons de tri
    "Ordem Alfabética": "Ordre Alphabétique",
    "Organizar cards em ordem alfabética (A-Z / Z-A)": "Trier les cartes par ordre alphabétique (A-Z / Z-A)",
    "Ordem de Criação": "Ordre de Création",
    "Organizar por data de criação e mostrar/ocultar data": "Trier par date de création et afficher/masquer la date",
    "Ordem Aleatória": "Ordre Aléatoire",
    "Organizar cards em ordem aleatória": "Trier les cartes en ordre aléatoire",
    "Mais Errados": "Plus d'Erreurs",
    "Organizar por cards mais errados (com mais lapsos)": "Trier par les cartes les plus échouées (avec plus d'oublis)",
    "Mais Certos": "Moins d'Erreurs",
    "Organizar por cards mais certos (com menos lapsos)": "Trier par les cartes les mieux réussies (avec moins d'oublis)",

    # Gestionnaire de Médias
    "Gerenciador de Mídia": "Gestionnaire de Médias",
    "Arquivos de Mídia Atuais": "Fichiers Médias Actuels",
    "Renomear": "Renommer",
    "Deletar": "Supprimer",
    "Deletar Todos": "Tout Supprimer",
    "Preview da Mídia": "Aperçu du Média",
    "Renomear Arquivo": "Renommer le Fichier",
    "Novo nome:": "Nouveau nom :",
    "Confirmar Exclusão": "Confirmer la Suppression",
    "Tem certeza de que deseja deletar o arquivo '{}'?": "Êtes-vous sûr de vouloir supprimer le fichier '{}' ?",
    "Tem certeza de que deseja deletar TODOS os {} arquivos de mídia?": "Êtes-vous sûr de vouloir supprimer TOUS les {} fichiers médias ?",
    "Arquivo renomeado de '{}' para '{}'.": "Fichier renommé de '{}' en '{}'.",
    "O nome '{}' já existe. Por favor, escolha outro nome.": "Le nom '{}' existe déjà. Veuillez choisir un autre nom.",
    "Erro ao renomear arquivo: {}": "Erreur lors du renommage du fichier : {}",
    "Arquivo '{}' deletado com sucesso.": "Fichier '{}' supprimé avec succès.",
    "Erro ao deletar arquivo: {}": "Erreur lors de la suppression du fichier : {}",
    "Todos os arquivos de mídia foram deletados.": "Tous les fichiers médias ont été supprimés.",
    "Nenhum arquivo de mídia para deletar.": "Aucun fichier média à supprimer.",

    # Visualiseur de Cartes
    "Visualizador de Cards": "Visualiseur de Cartes",
    "Gerar": "Générer",
    "Copiar para Área de Transferência": "Copier dans le Presse-papiers",
    "Salvar como HTML": "Enregistrer en HTML",
    "Impressão": "Imprimer",
    "Nenhum card para visualizar.": "Aucune carte à visualiser.",
    "Conteúdo copiado para a área de transferência!": "Contenu copié dans le presse-papiers !",
    "Salvar Arquivo HTML": "Enregistrer le Fichier HTML",
    "Arquivo HTML salvo em: {}": "Fichier HTML enregistré dans : {}",
    "Erro ao salvar arquivo: {}": "Erreur lors de l'enregistrement du fichier : {}",
    "Visualização de Impressão": "Aperçu avant impression",
    "Erro ao gerar preview de impressão: {}": "Erreur lors de la génération de l'aperçu avant impression : {}",

    # Mode Débutant
    "Modo Iniciante": "Mode Débutant",
    "Modo Completo": "Mode Complet",
    "Simplifica a interface para mostrar apenas as funções essenciais.": "Simplifie l'interface pour n'afficher que les fonctions essentielles.",
    "Mostra todas as ferramentas avançadas.": "Affiche tous les outils avancés.",
    "instructions_button": "Instructions",
    "instructions_title": "Instructions (Mode Débutant)",
    "beginner_instructions_line1": "<b>1. Une carte par ligne.</b>",
    "beginner_instructions_line2": "<b>2. Séparez le recto du verso avec un point-virgule ( ; ).</b>",
    "beginner_instructions_example_title": "Exemple :",
    "beginner_instructions_example_text": "Capitale de la France ; Paris",
}