# german.py

TRANSLATIONS = {
    # Hauptdialog
    "Adicionar Cards com Delimitadores": "Karten mit Trennzeichen hinzufügen",
    "Idioma:": "Sprache:",
    "Pronto": "Bereit",
    "Cards: {}": "Karten: {}",
    "Adicionar Imagem, Som ou Vídeo": "Bild, Ton oder Video hinzufügen",
    "Gerenciar Mídia": "Medien verwalten",
    "Exportar para HTML": "Als HTML exportieren",
    "Exportar cards para arquivo HTML": "Karten in eine HTML-Datei exportieren",
    "Visualizar Cards": "Karten ansehen",
    "Mostrar": "Anzeigen",
    "Mostra todos os cards do deck em 'Digite seus cards'": "Zeigt alle Karten des Stapels in 'Karten hier eingeben' an",
    "Editar": "Bearbeiten",
    "Parar Edição": "Bearbeitung beenden",
    "Ativa/desativa a edição em tempo real dos cards mostrados.": "Aktiviert/deaktiviert die Echtzeitbearbeitung der angezeigten Karten.",
    "Digite seus cards:": "Karten hier eingeben:",
    "Aplicar cor ao texto": "Textfarbe anwenden",
    "Aplicar cor de fundo ao texto": "Hintergrundfarbe anwenden",
    "Digite seus cards aqui...": "Geben Sie hier Ihre Karten ein...",
    "Etiquetas:": "Schlagwörter:",
    "Digite as etiquetas aqui (uma linha por card)...": "Geben Sie hier Schlagwörter ein (eine Zeile pro Karte)...",
    "Preview:": "Vorschau:",
    "Numerar Tags": "Schlagwörter nummerieren",
    "Repetir Tags": "Schlagwörter wiederholen",
    "Mostrar Etiquetas": "Schlagwörter anzeigen",
    "Ocultar Etiquetas": "Schlagwörter ausblenden",
    "Mudar Tema": "Thema ändern",
    "Tema Claro": "Helles Thema",
    "Tema Escuro": "Dunkles Thema",
    "📝 Editar em Grade": "📝 In Tabelle bearbeiten",
    "📄 Editar como Texto": "📄 Als Text bearbeiten",
    "Alterna entre a edição de texto livre e uma grade estilo planilha.": "Wechselt zwischen freier Texteingabe und einer tabellenartigen Ansicht.",
    "Juntar Linhas": "Zeilen verbinden",
    "Juntar todas as linhas": "Alle Zeilen verbinden",
    "Destaque": "Hervorheben",
    "Destacar texto (Ctrl+M)": "Text hervorheben (Strg+M)",
    "B": "F",
    "Negrito (Ctrl+B)": "Fett (Strg+B)",
    "I": "K",
    "Itálico (Ctrl+I)": "Kursiv (Strg+I)",
    "U": "U",
    "Sublinhado (Ctrl+U)": "Unterstrichen (Strg+U)",
    "Concatenar": "Verketten",
    "Concatenar texto": "Text verketten",
    "Limpar Tudo": "Alles löschen",
    "Limpar todos os campos e configurações": "Alle Felder und Einstellungen löschen",
    "Desfazer": "Rückgängig",
    "Desfazer (Ctrl+Z)": "Rückgängig (Strg+Z)",
    "Refazer": "Wiederholen",
    "Refazer (Ctrl+Y)": "Wiederholen (Strg+Y)",
    "Pesquisar... Ctrl+P": "Suchen... Strg+P",
    "Pesquisar": "Suchen",
    "Substituir tudo por... Ctrl+Shift+R": "Alles ersetzen durch... Strg+Umschalt+R",
    "Substituir Tudo": "Alles ersetzen",
    "Cloze 1 (Ctrl+Shift+D)": "Lückentext 1 (Strg+Umschalt+D)",
    "Adicionar Cloze 1 (Ctrl+Shift+D)": "Lückentext 1 hinzufügen (Strg+Umschalt+D)",
    "Cloze 2 (Ctrl+Shift+F)": "Lückentext 2 (Strg+Umschalt+F)",
    "Adicionar Cloze 2 (Ctrl+Shift+F)": "Lückentext 2 hinzufügen (Strg+Umschalt+F)",
    "Remover Cloze": "Lückentext entfernen",
    "Remover Cloze (sem atalho)": "Lückentext entfernen (kein Kürzel)",
    "Decks: {}": "Stapel: {}",
    "Pesquisar decks...": "Stapel suchen...",
    "Digite o nome do novo deck...": "Namen des neuen Stapels eingeben...",
    "Criar Deck": "Stapel erstellen",
    "Excluir Deck": "Stapel löschen",
    "Modelos ou Tipos de Notas: {}": "Notiztypen: {}",
    "Pesquisar tipos de notas...": "Notiztypen suchen...",
    "Mapeamento de Campos": "Feldzuordnung",
    "Associe cada parte a um campo:": "Ordnen Sie jeden Teil einem Feld zu:",
    "Parte {} -> Ignorar": "Teil {} -> Ignorieren",
    "Parte {} -> {}": "Teil {} -> {}",
    "Midia {}": "Medien {}",
    "Delimitadores:": "Trennzeichen:",
    "Tab": "Tabulator",
    "Vírgula": "Komma",
    "Ponto e Vírgula": "Semikolon",
    "Dois Pontos": "Doppelpunkt",
    "Interrogação": "Fragezeichen",
    "Barra": "Schrägstrich",
    "Exclamação": "Ausrufezeichen",
    "Pipe": "Pipe (|)",
    "Ocultar Decks/Modelos/Delimitadores": "Stapel/Modelle/Trennzeichen ausblenden",
    "Mostrar Decks/Modelos/Delimitadores": "Stapel/Modelle/Trennzeichen anzeigen",
    "Adicionar Cards (Ctrl+R)": "Karten hinzufügen (Strg+R)",
    "Salvando...": "Speichern...",
    "Salvo": "Gespeichert",
    "Erro ao salvar": "Fehler beim Speichern",
    "Selecione um modelo para ver a pré-visualização.": "Wählen Sie einen Notiztyp für die Vorschau aus.",
    "Erro:": "Fehler:",
    "Modelo não encontrado.": "Notiztyp nicht gefunden.",
    "Frente do Cartão (Preview)": "Vorderseite der Karte (Vorschau)",
    "Verso do Cartão (Preview)": "Rückseite der Karte (Vorschau)",
    "Erro na pré-visualização:": "Fehler in der Vorschau:",
    "Confirmação": "Bestätigung",
    "Tem certeza de que deseja limpar tudo? Isso não pode ser desfeito.": "Sind Sie sicher, dass Sie alles löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.",
    "Todos os campos e configurações foram limpos!": "Alle Felder und Einstellungen wurden gelöscht!",
    "Selecione um deck e um modelo!": "Wählen Sie einen Stapel und einen Notiztyp aus!",
    "Digite algum conteúdo!": "Geben Sie Inhalt ein!",
    "{} cards adicionados com sucesso!": "{} Karten erfolgreich hinzugefügt!",
    "Selecione um deck primeiro!": "Wählen Sie zuerst einen Stapel aus!",
    "Deck '{}' não encontrado!": "Stapel '{}' nicht gefunden!",
    "Nenhum card encontrado no deck '{}'!": "Keine Karten im Stapel '{}' gefunden!",
    "Erro ao salvar estado antes de 'Mostrar': {}": "Fehler beim Speichern des Zustands vor 'Anzeigen': {}",
    "Use a função 'Mostrar' para carregar os cards de um deck antes de editar.": "Verwenden Sie die Funktion 'Anzeigen', um Karten aus einem Stapel vor dem Bearbeiten zu laden.",
    "Modo de edição ativado.": "Bearbeitungsmodus aktiviert.",
    "Modo de edição desativado.": "Bearbeitungsmodus deaktiviert.",
    "O número de linhas foi alterado. Modo de edição desativado para evitar erros.": "Die Zeilenanzahl hat sich geändert. Bearbeitungsmodus zur Fehlervermeidung deaktiviert.",
    "Atualizando card...": "Karte wird aktualisiert...",
    "Card {} atualizado!": "Karte {} aktualisiert!",
    "Erro ao atualizar": "Fehler beim Aktualisieren",
    "Nenhum estado anterior salvo encontrado!": "Kein zuvor gespeicherter Zustand gefunden.",
    "Por favor, selecione uma célula na grade primeiro.": "Bitte wählen Sie zuerst eine Zelle in der Tabelle aus.",
    "Selecionar Mídia": "Medien auswählen",
    "🖼️ Adicionar Imagem/Mídia...": "🖼️ Bild/Medien hinzufügen...",
    "Colar HTML sem Tag e sem Formatação": "HTML ohne Tags und Formatierung einfügen",
    "Colar com Tags HTML": "Mit HTML-Tags einfügen",
    "Colar do Excel com Ponto e Vírgula": "Aus Excel mit Semikolon einfügen",
    "Colar do Word": "Aus Word einfügen",
    "Nenhuma imagem, texto ou HTML encontrado na área de transferência.": "Kein Bild, Text oder HTML in der Zwischenablage gefunden.",
    "Nenhum texto encontrado na área de transferência para colar como Excel.": "Kein Text in der Zwischenablage zum Einfügen als Excel gefunden.",
    "Nenhum texto encontrado na área de transferência para colar como Word.": "Kein Text in der Zwischenablage zum Einfügen als Word gefunden.",
    "Nenhum texto ou HTML encontrado na área de transferência.": "Kein Text oder HTML in der Zwischenablage gefunden.",
    "Erro na Exportação": "Exportfehler",
    "Ocorreu um erro durante a exportação: {}": "Beim Export ist ein Fehler aufgetreten: {}",
    "Por favor, insira um texto para pesquisar.": "Bitte geben Sie einen Suchtext ein.",
    "Texto '{}' não encontrado.": "Text '{}' nicht gefunden.",
    "Todas as ocorrências de '{}' foram substituídas por '{}'.": "Alle Vorkommen von '{}' wurden durch '{}' ersetzt.",
    "Todas as ocorrências de '{}' foram removidas.": "Alle Vorkommen von '{}' wurden entfernt.",
    "Por favor, insira um nome para o deck!": "Bitte geben Sie einen Namen für den Stapel ein!",
    "Erro ao criar o deck: {}": "Fehler beim Erstellen des Stapels: {}",
    "Etiquetas (Selecionado)": "Schlagwörter (Ausgewählt)",
    "Por favor, selecione uma palavra para adicionar o cloze.": "Bitte wählen Sie ein Wort aus, um den Lückentext hinzuzufügen.",
    "Erro ao carregar configurações: {}": "Fehler beim Laden der Einstellungen: {}",
    "Nenhum arquivo de mídia foi adicionado ou referenciado no texto!": "Keine Mediendateien im Text hinzugefügt oder referenziert!",
    "Selecionar Mídia para {}": "Medien für {} auswählen",
    "Ocultar Ferramentas": "Werkzeuge ausblenden",
    "Mostrar Ferramentas": "Werkzeuge anzeigen",
    "Campo {}": "Feld {}",
    "Confirmar Exclusão de Deck": "Löschen des Stapels bestätigen",
    "Você tem certeza que deseja excluir o deck '{}'?\n\nIsso excluirá permanentemente {} card(s) e suas mídias associadas (se não forem usadas em outros decks).\n\nESTA AÇÃO NÃO PODE SER DESFEITA.": "Sind Sie sicher, dass Sie den Stapel '{}' löschen möchten?\n\nDadurch werden {} Karte(n) und die zugehörigen Medien dauerhaft gelöscht (sofern sie nicht von anderen Stapeln verwendet werden).\n\DIESE AKTION KANN NICHT RÜCKGÄNGIG GEMACHT WERDEN.",
    "Ocorreu um erro ao excluir o deck: {}": "Beim Löschen des Stapels ist ein Fehler aufgetreten: {}",

    # Sortier-Schaltflächen
    "Ordem Alfabética": "Alphabetische Reihenfolge",
    "Organizar cards em ordem alfabética (A-Z / Z-A)": "Karten alphabetisch sortieren (A-Z / Z-A)",
    "Ordem de Criação": "Erstellungsdatum",
    "Organizar por data de criação e mostrar/ocultar data": "Nach Erstellungsdatum sortieren und Datum anzeigen/ausblenden",
    "Ordem Aleatória": "Zufällige Reihenfolge",
    "Organizar cards em ordem aleatória": "Karten zufällig sortieren",
    "Mais Errados": "Meiste Fehler",
    "Organizar por cards mais errados (com mais lapsos)": "Nach den am häufigsten falsch beantworteten Karten sortieren",
    "Mais Certos": "Wenigste Fehler",
    "Organizar por cards mais certos (com menos lapsos)": "Nach den am seltensten falsch beantworteten Karten sortieren",

    # Medien-Manager
    "Gerenciador de Mídia": "Medien-Manager",
    "Arquivos de Mídia Atuais": "Aktuelle Mediendateien",
    "Renomear": "Umbenennen",
    "Deletar": "Löschen",
    "Deletar Todos": "Alle löschen",
    "Preview da Mídia": "Medienvorschau",
    "Renomear Arquivo": "Datei umbenennen",
    "Novo nome:": "Neuer Name:",
    "Confirmar Exclusão": "Löschung bestätigen",
    "Tem certeza de que deseja deletar o arquivo '{}'?": "Sind Sie sicher, dass Sie die Datei '{}' löschen möchten?",
    "Tem certeza de que deseja deletar TODOS os {} arquivos de mídia?": "Sind Sie sicher, dass Sie ALLE {} Mediendateien löschen möchten?",
    "Arquivo renomeado de '{}' para '{}'.": "Datei von '{}' in '{}' umbenannt.",
    "O nome '{}' já existe. Por favor, escolha outro nome.": "Der Name '{}' existiert bereits. Bitte wählen Sie einen anderen Namen.",
    "Erro ao renomear arquivo: {}": "Fehler beim Umbenennen der Datei: {}",
    "Arquivo '{}' deletado com sucesso.": "Datei '{}' erfolgreich gelöscht.",
    "Erro ao deletar arquivo: {}": "Fehler beim Löschen der Datei: {}",
    "Todos os arquivos de mídia foram deletados.": "Alle Mediendateien wurden gelöscht.",
    "Nenhum arquivo de mídia para deletar.": "Keine Mediendateien zum Löschen vorhanden.",

    # Karten-Vorschau
    "Visualizador de Cards": "Karten-Vorschau",
    "Gerar": "Generieren",
    "Copiar para Área de Transferência": "In die Zwischenablage kopieren",
    "Salvar como HTML": "Als HTML speichern",
    "Impressão": "Drucken",
    "Nenhum card para visualizar.": "Keine Karten zur Ansicht vorhanden.",
    "Conteúdo copiado para a área de transferência!": "Inhalt in die Zwischenablage kopiert!",
    "Salvar Arquivo HTML": "HTML-Datei speichern",
    "Arquivo HTML salvo em: {}": "HTML-Datei gespeichert unter: {}",
    "Erro ao salvar arquivo: {}": "Fehler beim Speichern der Datei: {}",
    "Visualização de Impressão": "Druckvorschau",
    "Erro ao gerar preview de impressão: {}": "Fehler beim Erstellen der Druckvorschau: {}",

    # Anfängermodus
    "Modo Iniciante": "Anfängermodus",
    "Modo Completo": "Vollmodus",
    "Simplifica a interface para mostrar apenas as funções essenciais.": "Vereinfacht die Benutzeroberfläche, um nur die wesentlichen Funktionen anzuzeigen.",
    "Mostra todas as ferramentas avançadas.": "Zeigt alle erweiterten Werkzeuge an.",
    "instructions_button": "Anleitung",
    "instructions_title": "Anleitung (Anfängermodus)",
    "beginner_instructions_line1": "<b>1. Eine Karte pro Zeile.</b>",
    "beginner_instructions_line2": "<b>2. Trennen Sie die Vorder- von der Rückseite mit einem Semikolon ( ; ).</b>",
    "beginner_instructions_example_title": "Beispiel:",
    "beginner_instructions_example_text": "Hauptstadt von Deutschland; Berlin",
}