# indonesian.py

TRANSLATIONS = {
    # Dialog Utama
    "Adicionar Cards com Delimitadores": "Tambah Kartu dengan Pembatas",
    "Idioma:": "Bahasa:",
    "Pronto": "Siap",
    "Cards: {}": "Kartu: {}",
    "Adicionar Imagem, Som ou Vídeo": "Tambah Gambar, Suara, atau Video",
    "Gerenciar Mídia": "Kelola Media",
    "Exportar para HTML": "Ekspor ke HTML",
    "Exportar cards para arquivo HTML": "Ekspor kartu ke file HTML",
    "Visualizar Cards": "Lihat Kartu",
    "Mostrar": "Tampilkan",
    "Mostra todos os cards do deck em 'Digite seus cards'": "Tampilkan semua kartu dari dek di 'Masukkan kartu Anda'",
    "Editar": "Edit",
    "Parar Edição": "Hentikan Pengeditan",
    "Ativa/desativa a edição em tempo real dos cards mostrados.": "Mengaktifkan/menonaktifkan pengeditan real-time dari kartu yang ditampilkan.",
    "Digite seus cards:": "Masukkan kartu Anda:",
    "Aplicar cor ao texto": "Terapkan warna pada teks",
    "Aplicar cor de fundo ao texto": "Terapkan warna latar pada teks",
    "Digite seus cards aqui...": "Masukkan kartu Anda di sini...",
    "Etiquetas:": "Tag:",
    "Digite as etiquetas aqui (uma linha por card)...": "Masukkan tag di sini (satu baris per kartu)...",
    "Preview:": "Pratinjau:",
    "Numerar Tags": "Nomori Tag",
    "Repetir Tags": "Ulangi Tag",
    "Mostrar Etiquetas": "Tampilkan Tag",
    "Ocultar Etiquetas": "Sembunyikan Tag",
    "Mudar Tema": "Ubah Tema",
    "Tema Claro": "Tema Terang",
    "Tema Escuro": "Tema Gelap",
    "📝 Editar em Grade": "📝 Edit di Grid",
    "📄 Editar como Texto": "📄 Edit sebagai Teks",
    "Alterna entre a edição de texto livre e uma grade estilo planilha.": "Beralih antara pengeditan teks bebas dan grid gaya spreadsheet.",
    "Juntar Linhas": "Gabungkan Baris",
    "Juntar todas as linhas": "Gabungkan semua baris",
    "Destaque": "Sorot",
    "Destacar texto (Ctrl+M)": "Sorot teks (Ctrl+M)",
    "B": "T",
    "Negrito (Ctrl+B)": "Tebal (Ctrl+B)",
    "I": "M",
    "Itálico (Ctrl+I)": "Miring (Ctrl+I)",
    "U": "G",
    "Sublinhado (Ctrl+U)": "Garis Bawah (Ctrl+U)",
    "Concatenar": "Gabungkan",
    "Concatenar texto": "Gabungkan teks",
    "Limpar Tudo": "Bersihkan Semua",
    "Limpar todos os campos e configurações": "Bersihkan semua bidang dan pengaturan",
    "Desfazer": "Urungkan",
    "Desfazer (Ctrl+Z)": "Urungkan (Ctrl+Z)",
    "Refazer": "Ulangi",
    "Refazer (Ctrl+Y)": "Ulangi (Ctrl+Y)",
    "Pesquisar... Ctrl+P": "Cari... Ctrl+P",
    "Pesquisar": "Cari",
    "Substituir tudo por... Ctrl+Shift+R": "Ganti semua dengan... Ctrl+Shift+R",
    "Substituir Tudo": "Ganti Semua",
    "Cloze 1 (Ctrl+Shift+D)": "Cloze 1 (Ctrl+Shift+D)",
    "Adicionar Cloze 1 (Ctrl+Shift+D)": "Tambah Cloze 1 (Ctrl+Shift+D)",
    "Cloze 2 (Ctrl+Shift+F)": "Cloze 2 (Ctrl+Shift+F)",
    "Adicionar Cloze 2 (Ctrl+Shift+F)": "Tambah Cloze 2 (Ctrl+Shift+F)",
    "Remover Cloze": "Hapus Cloze",
    "Remover Cloze (sem atalho)": "Hapus Cloze (tanpa pintasan)",
    "Decks: {}": "Dek: {}",
    "Pesquisar decks...": "Cari dek...",
    "Digite o nome do novo deck...": "Masukkan nama dek baru...",
    "Criar Deck": "Buat Dek",
    "Excluir Deck": "Hapus Dek",
    "Modelos ou Tipos de Notas: {}": "Tipe Catatan: {}",
    "Pesquisar tipos de notas...": "Cari tipe catatan...",
    "Mapeamento de Campos": "Pemetaan Bidang",
    "Associe cada parte a um campo:": "Petakan setiap bagian ke sebuah bidang:",
    "Parte {} -> Ignorar": "Bagian {} -> Abaikan",
    "Parte {} -> {}": "Bagian {} -> {}",
    "Midia {}": "Media {}",
    "Delimitadores:": "Pembatas:",
    "Tab": "Tab",
    "Vírgula": "Koma",
    "Ponto e Vírgula": "Titik Koma",
    "Dois Pontos": "Titik Dua",
    "Interrogação": "Tanda Tanya",
    "Barra": "Garis Miring",
    "Exclamação": "Tanda Seru",
    "Pipe": "Pipa (|)",
    "Ocultar Decks/Modelos/Delimitadores": "Sembunyikan Dek/Model/Pembatas",
    "Mostrar Decks/Modelos/Delimitadores": "Tampilkan Dek/Model/Pembatas",
    "Adicionar Cards (Ctrl+R)": "Tambah Kartu (Ctrl+R)",
    "Salvando...": "Menyimpan...",
    "Salvo": "Tersimpan",
    "Erro ao salvar": "Gagal menyimpan",
    "Selecione um modelo para ver a pré-visualização.": "Pilih tipe catatan untuk melihat pratinjau.",
    "Erro:": "Kesalahan:",
    "Modelo não encontrado.": "Tipe catatan tidak ditemukan.",
    "Frente do Cartão (Preview)": "Depan Kartu (Pratinjau)",
    "Verso do Cartão (Preview)": "Belakang Kartu (Pratinjau)",
    "Erro na pré-visualização:": "Kesalahan pratinjau:",
    "Confirmação": "Konfirmasi",
    "Tem certeza de que deseja limpar tudo? Isso não pode ser desfeito.": "Apakah Anda yakin ingin membersihkan semuanya? Tindakan ini tidak dapat diurungkan.",
    "Todos os campos e configurações foram limpos!": "Semua bidang dan pengaturan telah dibersihkan!",
    "Selecione um deck e um modelo!": "Pilih dek dan tipe catatan!",
    "Digite algum conteúdo!": "Masukkan konten!",
    "{} cards adicionados com sucesso!": "{} kartu berhasil ditambahkan!",
    "Selecione um deck primeiro!": "Pilih dek terlebih dahulu!",
    "Deck '{}' não encontrado!": "Dek '{}' tidak ditemukan!",
    "Nenhum card encontrado no deck '{}'!": "Tidak ada kartu yang ditemukan di dek '{}'!",
    "Erro ao salvar estado antes de 'Mostrar': {}": "Gagal menyimpan status sebelum 'Tampilkan': {}",
    "Use a função 'Mostrar' para carregar os cards de um deck antes de editar.": "Gunakan fungsi 'Tampilkan' untuk memuat kartu dari dek sebelum mengedit.",
    "Modo de edição ativado.": "Mode edit diaktifkan.",
    "Modo de edição desativado.": "Mode edit dinonaktifkan.",
    "O número de linhas foi alterado. Modo de edição desativado para evitar erros.": "Jumlah baris telah berubah. Mode edit dinonaktifkan untuk menghindari kesalahan.",
    "Atualizando card...": "Memperbarui kartu...",
    "Card {} atualizado!": "Kartu {} diperbarui!",
    "Erro ao atualizar": "Gagal memperbarui",
    "Nenhum estado anterior salvo encontrado!": "Tidak ada status tersimpan sebelumnya yang ditemukan.",
    "Por favor, selecione uma célula na grade primeiro.": "Silakan pilih sel di grid terlebih dahulu.",
    "Selecionar Mídia": "Pilih Media",
    "🖼️ Adicionar Imagem/Mídia...": "🖼️ Tambah Gambar/Media...",
    "Colar HTML sem Tag e sem Formatação": "Tempel HTML tanpa Tag dan Format",
    "Colar com Tags HTML": "Tempel dengan Tag HTML",
    "Colar do Excel com Ponto e Vírgula": "Tempel dari Excel dengan Titik Koma",
    "Colar do Word": "Tempel dari Word",
    "Nenhuma imagem, texto ou HTML encontrado na área de transferência.": "Tidak ada gambar, teks, atau HTML yang ditemukan di papan klip.",
    "Nenhum texto encontrado na área de transferência para colar como Excel.": "Tidak ada teks yang ditemukan di papan klip untuk ditempel sebagai Excel.",
    "Nenhum texto encontrado na área de transferência para colar como Word.": "Tidak ada teks yang ditemukan di papan klip untuk ditempel sebagai Word.",
    "Nenhum texto ou HTML encontrado na área de transferência.": "Tidak ada teks atau HTML yang ditemukan di papan klip.",
    "Erro na Exportação": "Gagal Mengekspor",
    "Ocorreu um erro durante a exportação: {}": "Terjadi kesalahan saat mengekspor: {}",
    "Por favor, insira um texto para pesquisar.": "Silakan masukkan teks untuk mencari.",
    "Texto '{}' não encontrado.": "Teks '{}' tidak ditemukan.",
    "Todas as ocorrências de '{}' foram substituídas por '{}'.": "Semua kemunculan '{}' telah diganti dengan '{}'.",
    "Todas as ocorrências de '{}' foram removidas.": "Semua kemunculan '{}' telah dihapus.",
    "Por favor, insira um nome para o deck!": "Silakan masukkan nama untuk dek!",
    "Erro ao criar o deck: {}": "Gagal membuat dek: {}",
    "Etiquetas (Selecionado)": "Tag (Dipilih)",
    "Por favor, selecione uma palavra para adicionar o cloze.": "Silakan pilih kata untuk menambahkan cloze.",
    "Erro ao carregar configurações: {}": "Gagal memuat pengaturan: {}",
    "Nenhum arquivo de mídia foi adicionado ou referenciado no texto!": "Tidak ada file media yang ditambahkan atau direferensikan dalam teks!",
    "Selecionar Mídia para {}": "Pilih Media untuk {}",
    "Ocultar Ferramentas": "Sembunyikan Alat",
    "Mostrar Ferramentas": "Tampilkan Alat",
    "Campo {}": "Bidang {}",
    "Confirmar Exclusão de Deck": "Konfirmasi Penghapusan Dek",
    "Você tem certeza que deseja excluir o deck '{}'?\n\nIsso excluirá permanentemente {} card(s) e suas mídias associadas (se não forem usadas em outros decks).\n\nESTA AÇÃO NÃO PODE SER DESFEITA.": "Apakah Anda yakin ingin menghapus dek '{}'?\n\nIni akan menghapus secara permanen {} kartu dan media terkait (jika tidak digunakan oleh dek lain).\n\nTINDAKAN INI TIDAK DAPAT DIURUNGKAN.",
    "Ocorreu um erro ao excluir o deck: {}": "Terjadi kesalahan saat menghapus dek: {}",

    # Tombol Pengurutan
    "Ordem Alfabética": "Urutan Abjad",
    "Organizar cards em ordem alfabética (A-Z / Z-A)": "Urutkan kartu berdasarkan abjad (A-Z / Z-A)",
    "Ordem de Criação": "Urutan Pembuatan",
    "Organizar por data de criação e mostrar/ocultar data": "Urutkan berdasarkan tanggal pembuatan dan tampilkan/sembunyikan tanggal",
    "Ordem Aleatória": "Urutan Acak",
    "Organizar cards em ordem aleatória": "Urutkan kartu secara acak",
    "Mais Errados": "Paling Sering Salah",
    "Organizar por cards mais errados (com mais lapsos)": "Urutkan berdasarkan kartu yang paling sering salah (dengan lebih banyak kegagalan)",
    "Mais Certos": "Paling Jarang Salah",
    "Organizar por cards mais certos (com menos lapsos)": "Urutkan berdasarkan kartu yang paling jarang salah (dengan lebih sedikit kegagalan)",

    # Pengelola Media
    "Gerenciador de Mídia": "Pengelola Media",
    "Arquivos de Mídia Atuais": "File Media Saat Ini",
    "Renomear": "Ubah Nama",
    "Deletar": "Hapus",
    "Deletar Todos": "Hapus Semua",
    "Preview da Mídia": "Pratinjau Media",
    "Renomear Arquivo": "Ubah Nama File",
    "Novo nome:": "Nama baru:",
    "Confirmar Exclusão": "Konfirmasi Penghapusan",
    "Tem certeza de que deseja deletar o arquivo '{}'?": "Apakah Anda yakin ingin menghapus file '{}'?",
    "Tem certeza de que deseja deletar TODOS os {} arquivos de mídia?": "Apakah Anda yakin ingin menghapus SEMUA {} file media?",
    "Arquivo renomeado de '{}' para '{}'.": "File diubah namanya dari '{}' menjadi '{}'.",
    "O nome '{}' já existe. Por favor, escolha outro nome.": "Nama '{}' sudah ada. Silakan pilih nama lain.",
    "Erro ao renomear arquivo: {}": "Gagal mengubah nama file: {}",
    "Arquivo '{}' deletado com sucesso.": "File '{}' berhasil dihapus.",
    "Erro ao deletar arquivo: {}": "Gagal menghapus file: {}",
    "Todos os arquivos de mídia foram deletados.": "Semua file media telah dihapus.",
    "Nenhum arquivo de mídia para deletar.": "Tidak ada file media untuk dihapus.",

    # Penampil Kartu
    "Visualizador de Cards": "Penampil Kartu",
    "Gerar": "Hasilkan",
    "Copiar para Área de Transferência": "Salin ke Papan Klip",
    "Salvar como HTML": "Simpan sebagai HTML",
    "Impressão": "Cetak",
    "Nenhum card para visualizar.": "Tidak ada kartu untuk ditampilkan.",
    "Conteúdo copiado para a área de transferência!": "Konten disalin ke papan klip!",
    "Salvar Arquivo HTML": "Simpan File HTML",
    "Arquivo HTML salvo em: {}": "File HTML disimpan di: {}",
    "Erro ao salvar arquivo: {}": "Gagal menyimpan file: {}",
    "Visualização de Impressão": "Pratinjau Cetak",
    "Erro ao gerar preview de impressão: {}": "Gagal menghasilkan pratinjau cetak: {}",

    # Mode Pemula
    "Modo Iniciante": "Mode Pemula",
    "Modo Completo": "Mode Lengkap",
    "Simplifica a interface para mostrar apenas as funções essenciais.": "Menyederhanakan antarmuka untuk hanya menampilkan fungsi-fungsi penting.",
    "Mostra todas as ferramentas avançadas.": "Menampilkan semua alat canggih.",
    "instructions_button": "Instruksi",
    "instructions_title": "Instruksi (Mode Pemula)",
    "beginner_instructions_line1": "<b>1. Satu kartu per baris.</b>",
    "beginner_instructions_line2": "<b>2. Pisahkan bagian depan dan belakang dengan titik koma ( ; ).</b>",
    "beginner_instructions_example_title": "Contoh:",
    "beginner_instructions_example_text": "Ibu kota Indonesia ; Jakarta",
}