# italian.py

TRANSLATIONS = {
    # Finestra Principale
    "Adicionar Cards com Delimitadores": "Aggiungi Schede con Delimitatori",
    "Idioma:": "Lingua:",
    "Pronto": "Pronto",
    "Cards: {}": "Schede: {}",
    "Adicionar Imagem, Som ou Vídeo": "Aggiungi Immagine, Suono o Video",
    "Gerenciar Mídia": "Gestisci File Multimediali",
    "Exportar para HTML": "Esporta in HTML",
    "Exportar cards para arquivo HTML": "Esporta le schede in un file HTML",
    "Visualizar Cards": "Visualizza Schede",
    "Mostrar": "Mostra",
    "Mostra todos os cards do deck em 'Digite seus cards'": "Mostra tutte le schede del mazzo in 'Inserisci le tue schede'",
    "Editar": "Modifica",
    "Parar Edição": "Interrompi Modifica",
    "Ativa/desativa a edição em tempo real dos cards mostrados.": "Abilita/disabilita la modifica in tempo reale delle schede visualizzate.",
    "Digite seus cards:": "Inserisci le tue schede:",
    "Aplicar cor ao texto": "Applica colore al testo",
    "Aplicar cor de fundo ao texto": "Applica colore di sfondo al testo",
    "Digite seus cards aqui...": "Inserisci qui le tue schede...",
    "Etiquetas:": "Etichette:",
    "Digite as etiquetas aqui (uma linha por card)...": "Inserisci le etichette qui (una riga per scheda)...",
    "Preview:": "Anteprima:",
    "Numerar Tags": "Numera Etichette",
    "Repetir Tags": "Ripeti Etichette",
    "Mostrar Etiquetas": "Mostra Etichette",
    "Ocultar Etiquetas": "Nascondi Etichette",
    "Mudar Tema": "Cambia Tema",
    "Tema Claro": "Tema Chiaro",
    "Tema Escuro": "Tema Scuro",
    "📝 Editar em Grade": "📝 Modifica in Griglia",
    "📄 Editar como Texto": "📄 Modifica come Testo",
    "Alterna entre a edição de texto livre e uma grade estilo planilha.": "Alterna tra la modifica di testo libero e una griglia in stile foglio di calcolo.",
    "Juntar Linhas": "Unisci Righe",
    "Juntar todas as linhas": "Unisci tutte le righe",
    "Destaque": "Evidenzia",
    "Destacar texto (Ctrl+M)": "Evidenzia testo (Ctrl+M)",
    "B": "G",
    "Negrito (Ctrl+B)": "Grassetto (Ctrl+B)",
    "I": "C",
    "Itálico (Ctrl+I)": "Corsivo (Ctrl+I)",
    "U": "S",
    "Sublinhado (Ctrl+U)": "Sottolineato (Ctrl+U)",
    "Concatenar": "Concatena",
    "Concatenar texto": "Concatena testo",
    "Limpar Tudo": "Pulisci Tutto",
    "Limpar todos os campos e configurações": "Pulisci tutti i campi e le impostazioni",
    "Desfazer": "Annulla",
    "Desfazer (Ctrl+Z)": "Annulla (Ctrl+Z)",
    "Refazer": "Ripristina",
    "Refazer (Ctrl+Y)": "Ripristina (Ctrl+Y)",
    "Pesquisar... Ctrl+P": "Cerca... Ctrl+P",
    "Pesquisar": "Cerca",
    "Substituir tudo por... Ctrl+Shift+R": "Sostituisci tutto con... Ctrl+Shift+R",
    "Substituir Tudo": "Sostituisci Tutto",
    "Cloze 1 (Ctrl+Shift+D)": "Cloze 1 (Ctrl+Shift+D)",
    "Adicionar Cloze 1 (Ctrl+Shift+D)": "Aggiungi Cloze 1 (Ctrl+Shift+D)",
    "Cloze 2 (Ctrl+Shift+F)": "Cloze 2 (Ctrl+Shift+F)",
    "Adicionar Cloze 2 (Ctrl+Shift+F)": "Aggiungi Cloze 2 (Ctrl+Shift+F)",
    "Remover Cloze": "Rimuovi Cloze",
    "Remover Cloze (sem atalho)": "Rimuovi Cloze (senza scorciatoia)",
    "Decks: {}": "Mazzi: {}",
    "Pesquisar decks...": "Cerca mazzi...",
    "Digite o nome do novo deck...": "Inserisci il nome del nuovo mazzo...",
    "Criar Deck": "Crea Mazzo",
    "Excluir Deck": "Elimina Mazzo",
    "Modelos ou Tipos de Notas: {}": "Tipi di Nota: {}",
    "Pesquisar tipos de notas...": "Cerca tipi di nota...",
    "Mapeamento de Campos": "Mappatura Campi",
    "Associe cada parte a um campo:": "Associa ogni parte a un campo:",
    "Parte {} -> Ignorar": "Parte {} -> Ignora",
    "Parte {} -> {}": "Parte {} -> {}",
    "Midia {}": "File {}",
    "Delimitadores:": "Delimitatori:",
    "Tab": "Tabulazione",
    "Vírgula": "Virgola",
    "Ponto e Vírgula": "Punto e Virgola",
    "Dois Pontos": "Due Punti",
    "Interrogação": "Punto Interrogativo",
    "Barra": "Barra",
    "Exclamação": "Punto Esclamativo",
    "Pipe": "Pipe (|)",
    "Ocultar Decks/Modelos/Delimitadores": "Nascondi Mazzi/Modelli/Delimitatori",
    "Mostrar Decks/Modelos/Delimitadores": "Mostra Mazzi/Modelli/Delimitatori",
    "Adicionar Cards (Ctrl+R)": "Aggiungi Schede (Ctrl+R)",
    "Salvando...": "Salvataggio...",
    "Salvo": "Salvato",
    "Erro ao salvar": "Errore durante il salvataggio",
    "Selecione um modelo para ver a pré-visualização.": "Seleziona un tipo di nota per vedere l'anteprima.",
    "Erro:": "Errore:",
    "Modelo não encontrado.": "Tipo di nota non trovato.",
    "Frente do Cartão (Preview)": "Fronte della Scheda (Anteprima)",
    "Verso do Cartão (Preview)": "Retro della Scheda (Anteprima)",
    "Erro na pré-visualização:": "Errore nell'anteprima:",
    "Confirmação": "Conferma",
    "Tem certeza de que deseja limpar tudo? Isso não pode ser desfeito.": "Sei sicuro di voler cancellare tutto? Questa azione non può essere annullata.",
    "Todos os campos e configurações foram limpos!": "Tutti i campi e le impostazioni sono stati cancellati!",
    "Selecione um deck e um modelo!": "Seleziona un mazzo e un tipo di nota!",
    "Digite algum conteúdo!": "Inserisci del contenuto!",
    "{} cards adicionados com sucesso!": "{} schede aggiunte con successo!",
    "Selecione um deck primeiro!": "Seleziona prima un mazzo!",
    "Deck '{}' não encontrado!": "Mazzo '{}' non trovato!",
    "Nenhum card encontrado no deck '{}'!": "Nessuna scheda trovata nel mazzo '{}'!",
    "Erro ao salvar estado antes de 'Mostrar': {}": "Errore nel salvataggio dello stato prima di 'Mostra': {}",
    "Use a função 'Mostrar' para carregar os cards de um deck antes de editar.": "Usa la funzione 'Mostra' per caricare le schede da un mazzo prima di modificare.",
    "Modo de edição ativado.": "Modalità di modifica attivata.",
    "Modo de edição desativado.": "Modalità di modifica disattivata.",
    "O número de linhas foi alterado. Modo de edição desativado para evitar erros.": "Il numero di righe è cambiato. Modalità di modifica disattivata per prevenire errori.",
    "Atualizando card...": "Aggiornamento scheda...",
    "Card {} atualizado!": "Scheda {} aggiornata!",
    "Erro ao atualizar": "Errore durante l'aggiornamento",
    "Nenhum estado anterior salvo encontrado!": "Nessuno stato precedente salvato trovato.",
    "Por favor, selecione uma célula na grade primeiro.": "Seleziona prima una cella nella griglia.",
    "Selecionar Mídia": "Seleziona File",
    "🖼️ Adicionar Imagem/Mídia...": "🖼️ Aggiungi Immagine/File...",
    "Colar HTML sem Tag e sem Formatação": "Incolla HTML senza Tag e Formattazione",
    "Colar com Tags HTML": "Incolla con Tag HTML",
    "Colar do Excel com Ponto e Vírgula": "Incolla da Excel con Punto e Virgola",
    "Colar do Word": "Incolla da Word",
    "Nenhuma imagem, texto ou HTML encontrado na área de transferência.": "Nessuna immagine, testo o HTML trovato negli appunti.",
    "Nenhum texto encontrado na área de transferência para colar como Excel.": "Nessun testo trovato negli appunti da incollare come Excel.",
    "Nenhum texto encontrado na área de transferência para colar como Word.": "Nessun testo trovato negli appunti da incollare come Word.",
    "Nenhum texto ou HTML encontrado na área de transferência.": "Nessun testo o HTML trovato negli appunti.",
    "Erro na Exportação": "Errore di Esportazione",
    "Ocorreu um erro durante a exportação: {}": "Si è verificato un errore durante l'esportazione: {}",
    "Por favor, insira um texto para pesquisar.": "Inserisci un testo da cercare.",
    "Texto '{}' não encontrado.": "Testo '{}' non trovato.",
    "Toda as ocorrências de '{}' foram substituídas por '{}'.": "Tutte le occorrenze di '{}' sono state sostituite con '{}'.",
    "Todas as ocorrências de '{}' foram removidas.": "Tutte le occorrenze di '{}' sono state rimosse.",
    "Por favor, insira um nome para o deck!": "Inserisci un nome per il mazzo!",
    "Erro ao criar o deck: {}": "Errore nella creazione del mazzo: {}",
    "Etiquetas (Selecionado)": "Etichette (Selezionato)",
    "Por favor, selecione uma palavra para adicionar o cloze.": "Seleziona una parola per aggiungere il cloze.",
    "Erro ao carregar configurações: {}": "Errore nel caricamento delle impostazioni: {}",
    "Nenhum arquivo de mídia foi adicionado ou referenciado no texto!": "Nessun file multimediale è stato aggiunto o referenziato nel testo!",
    "Selecionar Mídia para {}": "Seleziona File per {}",
    "Ocultar Ferramentas": "Nascondi Strumenti",
    "Mostrar Ferramentas": "Mostra Strumenti",
    "Campo {}": "Campo {}",
    "Confirmar Exclusão de Deck": "Conferma Eliminazione Mazzo",
    "Você tem certeza que deseja excluir o deck '{}'?\n\nIsso excluirá permanentemente {} card(s) e suas mídias associadas (se não forem usadas em outros decks).\n\nESTA AÇÃO NÃO PODE SER DESFEITA.": "Sei sicuro di voler eliminare il mazzo '{}'?\n\nQuesto eliminerà permanentemente {} scheda(e) e i relativi file multimediali (se non utilizzati da altri mazzi).\n\nQUESTA AZIONE NON PUÒ ESSERE ANNULLATA.",
    "Ocorreu um erro ao excluir o deck: {}": "Si è verificato un errore durante l'eliminazione del mazzo: {}",

    # Pulsanti di ordinamento
    "Ordem Alfabética": "Ordine Alfabetico",
    "Organizar cards em ordem alfabética (A-Z / Z-A)": "Ordina le schede in ordine alfabetico (A-Z / Z-A)",
    "Ordem de Criação": "Ordine di Creazione",
    "Organizar por data de criação e mostrar/ocultar data": "Ordina per data di creazione e mostra/nascondi data",
    "Ordem Aleatória": "Ordine Casuale",
    "Organizar cards em ordem aleatória": "Ordina le schede in ordine casuale",
    "Mais Errados": "Più Errori",
    "Organizar por cards mais errados (com mais lapsos)": "Ordina per le schede con più errori (con più fallimenti)",
    "Mais Certos": "Meno Errori",
    "Organizar por cards mais certos (com menos lapsos)": "Ordina per le schede con meno errori (con meno fallimenti)",

    # Gestore Multimedia
    "Gerenciador de Mídia": "Gestore Multimedia",
    "Arquivos de Mídia Atuais": "File Multimediali Attuali",
    "Renomear": "Rinomina",
    "Deletar": "Elimina",
    "Deletar Todos": "Elimina Tutti",
    "Preview da Mídia": "Anteprima File",
    "Renomear Arquivo": "Rinomina File",
    "Novo nome:": "Nuovo nome:",
    "Confirmar Exclusão": "Conferma Eliminazione",
    "Tem certeza de que deseja deletar o arquivo '{}'?": "Sei sicuro di voler eliminare il file '{}'?",
    "Tem certeza de que deseja deletar TODOS os {} arquivos de mídia?": "Sei sicuro di voler eliminare TUTTI i {} file multimediali?",
    "Arquivo renomeado de '{}' para '{}'.": "File rinominato da '{}' a '{}'.",
    "O nome '{}' já existe. Por favor, escolha outro nome.": "Il nome '{}' esiste già. Scegli un altro nome.",
    "Erro ao renomear arquivo: {}": "Errore nel rinominare il file: {}",
    "Arquivo '{}' deletado com sucesso.": "File '{}' eliminato con successo.",
    "Erro ao deletar arquivo: {}": "Errore nell'eliminare il file: {}",
    "Todos os arquivos de mídia foram deletados.": "Tutti i file multimediali sono stati eliminati.",
    "Nenhum arquivo de mídia para deletar.": "Nessun file multimediale da eliminare.",

    # Visualizzatore Schede
    "Visualizador de Cards": "Visualizzatore Schede",
    "Gerar": "Genera",
    "Copiar para Área de Transferência": "Copia negli Appunti",
    "Salvar como HTML": "Salva come HTML",
    "Impressão": "Stampa",
    "Nenhum card para visualizar.": "Nessuna scheda da visualizzare.",
    "Conteúdo copiado para a área de transferência!": "Contenuto copiato negli appunti!",
    "Salvar Arquivo HTML": "Salva File HTML",
    "Arquivo HTML salvo em: {}": "File HTML salvato in: {}",
    "Erro ao salvar arquivo: {}": "Errore nel salvataggio del file: {}",
    "Visualização de Impressão": "Anteprima di Stampa",
    "Erro ao gerar preview de impressão: {}": "Errore nella generazione dell'anteprima di stampa: {}",

    # Modalità Principiante
    "Modo Iniciante": "Modalità Principiante",
    "Modo Completo": "Modalità Completa",
    "Simplifica a interface para mostrar apenas as funções essenciais.": "Semplifica l'interfaccia per mostrare solo le funzioni essenziali.",
    "Mostra todas as ferramentas avançadas.": "Mostra tutti gli strumenti avanzati.",
    "instructions_button": "Istruzioni",
    "instructions_title": "Istruzioni (Modalità Principiante)",
    "beginner_instructions_line1": "<b>1. Una scheda per riga.</b>",
    "beginner_instructions_line2": "<b>2. Separa il fronte dal retro con un punto e virgola ( ; ).</b>",
    "beginner_instructions_example_title": "Esempio:",
    "beginner_instructions_example_text": "capitale d'Italia ; Roma",
}