# japanese.py

TRANSLATIONS = {
    # Main Dialog
    "Adicionar Cards com Delimitadores": "区切り文字でカードを追加",
    "Idioma:": "言語:",
    "Pronto": "準備完了",
    "Cards: {}": "カード: {}",
    "Adicionar Imagem, Som ou Vídeo": "画像、音声、動画を追加",
    "Gerenciar Mídia": "メディアを管理",
    "Exportar para HTML": "HTMLにエクスポート",
    "Exportar cards para arquivo HTML": "カードをHTMLファイルにエクスポート",
    "Visualizar Cards": "カードをプレビュー",
    "Mostrar": "表示",
    "Mostra todos os cards do deck em 'Digite seus cards'": "デッキのすべてのカードを「カード入力」欄に表示します",
    "Editar": "編集",
    "Parar Edição": "編集を停止",
    "Ativa/desativa a edição em tempo real dos cards mostrados.": "表示されているカードのリアルタイム編集を有効/無効にします。",
    "Digite seus cards:": "カードを入力:",
    "Aplicar cor ao texto": "テキストに色を適用",
    "Aplicar cor de fundo ao texto": "テキストに背景色を適用",
    "Digite seus cards aqui...": "ここにカードを入力してください...",
    "Etiquetas:": "タグ:",
    "Digite as etiquetas aqui (uma linha por card)...": "ここにタグを入力（カードごとに1行）...",
    "Preview:": "プレビュー:",
    "Numerar Tags": "タグに番号を振る",
    "Repetir Tags": "タグを繰り返す",
    "Mostrar Etiquetas": "タグを表示",
    "Ocultar Etiquetas": "タグを非表示",
    "Mudar Tema": "テーマを変更",
    "Tema Claro": "ライトテーマ",
    "Tema Escuro": "ダークテーマ",
    "📝 Editar em Grade": "📝 グリッドで編集",
    "📄 Editar como Texto": "📄 テキストで編集",
    "Alterna entre a edição de texto livre e uma grade estilo planilha.": "フリーテキスト編集と表形式のグリッド編集を切り替えます。",
    "Juntar Linhas": "行を結合",
    "Juntar todas as linhas": "すべての行を結合",
    "Destaque": "ハイライト",
    "Destacar texto (Ctrl+M)": "テキストをハイライト (Ctrl+M)",
    "B": "B",
    "Negrito (Ctrl+B)": "太字 (Ctrl+B)",
    "I": "I",
    "Itálico (Ctrl+I)": "斜体 (Ctrl+I)",
    "U": "U",
    "Sublinhado (Ctrl+U)": "下線 (Ctrl+U)",
    "Concatenar": "連結",
    "Concatenar texto": "テキストを連結",
    "Limpar Tudo": "すべてクリア",
    "Limpar todos os campos e configurações": "すべてのフィールドと設定をクリア",
    "Desfazer": "元に戻す",
    "Desfazer (Ctrl+Z)": "元に戻す (Ctrl+Z)",
    "Refazer": "やり直し",
    "Refazer (Ctrl+Y)": "やり直し (Ctrl+Y)",
    "Pesquisar... Ctrl+P": "検索... Ctrl+P",
    "Pesquisar": "検索",
    "Substituir tudo por... Ctrl+Shift+R": "すべて置換... Ctrl+Shift+R",
    "Substituir Tudo": "すべて置換",
    "Cloze 1 (Ctrl+Shift+D)": "穴埋め1 (Ctrl+Shift+D)",
    "Adicionar Cloze 1 (Ctrl+Shift+D)": "穴埋め1を追加 (Ctrl+Shift+D)",
    "Cloze 2 (Ctrl+Shift+F)": "穴埋め2 (Ctrl+Shift+F)",
    "Adicionar Cloze 2 (Ctrl+Shift+F)": "穴埋め2を追加 (Ctrl+Shift+F)",
    "Remover Cloze": "穴埋めを削除",
    "Remover Cloze (sem atalho)": "穴埋めを削除 (ショートカットなし)",
    "Decks: {}": "デッキ: {}",
    "Pesquisar decks...": "デッキを検索...",
    "Digite o nome do novo deck...": "新しいデッキ名を入力...",
    "Criar Deck": "デッキを作成",
    "Excluir Deck": "デッキを削除",
    "Modelos ou Tipos de Notas: {}": "ノートタイプ: {}",
    "Pesquisar tipos de notas...": "ノートタイプを検索...",
    "Mapeamento de Campos": "フィールドマッピング",
    "Associe cada parte a um campo:": "各部分をフィールドに割り当て:",
    "Parte {} -> Ignorar": "部分 {} -> 無視",
    "Parte {} -> {}": "部分 {} -> {}",
    "Midia {}": "メディア {}",
    "Delimitadores:": "区切り文字:",
    "Tab": "タブ",
    "Vírgula": "コンマ",
    "Ponto e Vírgula": "セミコロン",
    "Dois Pontos": "コロン",
    "Interrogação": "疑問符",
    "Barra": "スラッシュ",
    "Exclamação": "感嘆符",
    "Pipe": "パイプ",
    "Ocultar Decks/Modelos/Delimitadores": "デッキ/モデル/区切り文字を非表示",
    "Mostrar Decks/Modelos/Delimitadores": "デッキ/モデル/区切り文字を表示",
    "Adicionar Cards (Ctrl+R)": "カードを追加 (Ctrl+R)",
    "Salvando...": "保存中...",
    "Salvo": "保存済み",
    "Erro ao salvar": "保存エラー",
    "Selecione um modelo para ver a pré-visualização.": "プレビューするにはノートタイプを選択してください。",
    "Erro:": "エラー:",
    "Modelo não encontrado.": "ノートタイプが見つかりません。",
    "Frente do Cartão (Preview)": "カードの表 (プレビュー)",
    "Verso do Cartão (Preview)": "カードの裏 (プレビュー)",
    "Erro na pré-visualização:": "プレビューエラー:",
    "Confirmação": "確認",
    "Tem certeza de que deseja limpar tudo? Isso não pode ser desfeito.": "すべてクリアしてもよろしいですか？この操作は元に戻せません。",
    "Todos os campos e configurações foram limpos!": "すべてのフィールドと設定がクリアされました！",
    "Selecione um deck e um modelo!": "デッキとノートタイプを選択してください！",
    "Digite algum conteúdo!": "何かコンテンツを入力してください！",
    "{} cards adicionados com sucesso!": "{}枚のカードが正常に追加されました！",
    "Selecione um deck primeiro!": "最初にデッキを選択してください！",
    "Deck '{}' não encontrado!": "デッキ「{}」が見つかりません！",
    "Nenhum card encontrado no deck '{}'!": "デッキ「{}」にカードが見つかりません！",
    "Erro ao salvar estado antes de 'Mostrar': {}": "「表示」前の状態保存中にエラーが発生しました: {}",
    "Use a função 'Mostrar' para carregar os cards de um deck antes de editar.": "編集する前に「表示」機能を使ってデッキからカードを読み込んでください。",
    "Modo de edição ativado.": "編集モードが有効です。",
    "Modo de edição desativado.": "編集モードが無効です。",
    "O número de linhas foi alterado. Modo de edição desativado para evitar erros.": "行数が変更されました。エラーを防ぐため編集モードを無効にしました。",
    "Atualizando card...": "カードを更新中...",
    "Card {} atualizado!": "カード {} を更新しました！",
    "Erro ao atualizar": "更新エラー",
    "Nenhum estado anterior salvo encontrado!": "保存された以前の状態が見つかりません！",
    "Por favor, selecione uma célula na grade primeiro.": "最初にグリッド内のセルを選択してください。",
    "Selecionar Mídia": "メディアを選択",
    "🖼️ Adicionar Imagem/Mídia...": "🖼️ 画像/メディアを追加...",
    "Colar HTML sem Tag e sem Formatação": "タグと書式なしでHTMLを貼り付け",
    "Colar com Tags HTML": "HTMLタグ付きで貼り付け",
    "Colar do Excel com Ponto e Vírgula": "Excelからセミコロン付きで貼り付け",
    "Colar do Word": "Wordから貼り付け",
    "Nenhuma imagem, texto ou HTML encontrado na área de transferência.": "クリップボードに画像、テキスト、またはHTMLが見つかりません。",
    "Nenhum texto encontrado na área de transferência para colar como Excel.": "Excelとして貼り付けるテキストがクリップボードに見つかりません。",
    "Nenhum texto encontrado na área de transferência para colar como Word.": "Wordとして貼り付けるテキストがクリップボードに見つかりません。",
    "Nenhum texto ou HTML encontrado na área de transferência.": "クリップボードにテキストまたはHTMLが見つかりません。",
    "Erro na Exportação": "エクスポートエラー",
    "Ocorreu um erro durante a exportação: {}": "エクスポート中にエラーが発生しました: {}",
    "Por favor, insira um texto para pesquisar.": "検索するテキストを入力してください。",
    "Texto '{}' não encontrado.": "テキスト「{}」が見つかりません。",
    "Todas as ocorrências de '{}' foram substituídas por '{}'.": "「{}」のすべての出現箇所が「{}」に置換されました。",
    "Todas as ocorrências de '{}' foram removidas.": "「{}」のすべての出現箇所が削除されました。",
    "Por favor, insira um nome para o deck!": "デッキ名を入力してください！",
    "Erro ao criar o deck: {}": "デッキの作成中にエラーが発生しました: {}",
    "Etiquetas (Selecionado)": "タグ (選択中)",
    "Por favor, selecione uma palavra para adicionar o cloze.": "穴埋めする単語を選択してください。",
    "Erro ao carregar configurações: {}": "設定の読み込み中にエラーが発生しました: {}",
    "Nenhum arquivo de mídia foi adicionado ou referenciado no texto!": "メディアファイルが追加またはテキスト内で参照されていません！",
    "Selecionar Mídia para {}": "{}用のメディアを選択",
    "Ocultar Ferramentas": "ツールを非表示",
    "Mostrar Ferramentas": "ツールを表示",
    "Campo {}": "フィールド {}",
    "Confirmar Exclusão de Deck": "デッキ削除の確認",
    "Você tem certeza que deseja excluir o deck '{}'?\n\nIsso excluirá permanentemente {} card(s) e suas mídias associadas (se não forem usadas em outros decks).\n\nESTA AÇÃO NÃO PODE SER DESFEITA.": "デッキ「{}」を削除してもよろしいですか？\n\nこれにより、{}枚のカードと関連メディア（他のデッキで使用されていない場合）が完全に削除されます。\n\nこの操作は元に戻せません。",
    "Ocorreu um erro ao excluir o deck: {}": "デッキの削除中にエラーが発生しました: {}",

    # New sorting buttons
    "Ordem Alfabética": "アルファベット順",
    "Organizar cards em ordem alfabética (A-Z / Z-A)": "カードをアルファベット順（A-Z / Z-A）に並べ替え",
    "Ordem de Criação": "作成日順",
    "Organizar por data de criação e mostrar/ocultar data": "作成日順に並べ替え、日付の表示/非表示を切り替え",
    "Ordem Aleatória": "ランダム順",
    "Organizar cards em ordem aleatória": "カードをランダムな順序に並べ替え",
    "Mais Errados": "間違いが多い順",
    "Organizar por cards mais errados (com mais lapsos)": "間違い（失敗）が多いカード順に並べ替え",
    "Mais Certos": "間違いが少ない順",
    "Organizar por cards mais certos (com menos lapsos)": "間違い（失敗）が少ないカード順に並べ替え",

    # Media Manager Dialog
    "Gerenciador de Mídia": "メディアマネージャー",
    "Arquivos de Mídia Atuais": "現在のメディアファイル",
    "Renomear": "名前を変更",
    "Deletar": "削除",
    "Deletar Todos": "すべて削除",
    "Preview da Mídia": "メディアプレビュー",
    "Renomear Arquivo": "ファイル名を変更",
    "Novo nome:": "新しい名前:",
    "Confirmar Exclusão": "削除の確認",
    "Tem certeza de que deseja deletar o arquivo '{}'?": "ファイル「{}」を削除してもよろしいですか？",
    "Tem certeza de que deseja deletar TODOS os {} arquivos de mídia?": "{}個のメディアファイルをすべて削除してもよろしいですか？",
    "Arquivo renomeado de '{}' para '{}'.": "ファイル名を「{}」から「{}」に変更しました。",
    "O nome '{}' já existe. Por favor, escolha outro nome.": "名前「{}」はすでに存在します。別の名前を選択してください。",
    "Erro ao renomear arquivo: {}": "ファイル名の変更中にエラーが発生しました: {}",
    "Arquivo '{}' deletado com sucesso.": "ファイル「{}」が正常に削除されました。",
    "Erro ao deletar arquivo: {}": "ファイルの削除中にエラーが発生しました: {}",
    "Todos os arquivos de mídia foram deletados.": "すべてのメディアファイルが削除されました。",
    "Nenhum arquivo de mídia para deletar.": "削除するメディアファイルはありません。",

    # Card Viewer Dialog
    "Visualizador de Cards": "カードビューア",
    "Gerar": "生成",
    "Copiar para Área de Transferência": "クリップボードにコピー",
    "Salvar como HTML": "HTMLとして保存",
    "Impressão": "印刷",
    "Nenhum card para visualizar.": "表示するカードはありません。",
    "Conteúdo copiado para a área de transferência!": "コンテンツがクリップボードにコピーされました！",
    "Salvar Arquivo HTML": "HTMLファイルを保存",
    "Arquivo HTML salvo em: {}": "HTMLファイルを{}に保存しました",
    "Erro ao salvar arquivo: {}": "ファイルの保存中にエラーが発生しました: {}",
    "Visualização de Impressão": "印刷プレビュー",
    "Erro ao gerar preview de impressão: {}": "印刷プレビューの生成中にエラーが発生しました: {}",


    "Modo Iniciante": "初心者モード",
    "Modo Completo": "フルモード",
    "Simplifica a interface para mostrar apenas as funções essenciais.": "インターフェースを簡素化し、基本的な機能のみを表示します。",
    "Mostra todas as ferramentas avançadas.": "すべての高度なツールを表示します。",


    "instructions_button": "説明",
    "instructions_title": "説明 (初心者モード)",
    "beginner_instructions_line1": "<b>1. 1行に1枚のカード。</b>",
    "beginner_instructions_line2": "<b>2. 表と裏をセミコロン（ ; ）で区切ります。</b>",
    "beginner_instructions_example_title": "例：",
    "beginner_instructions_example_text": "日本の首都 ; 東京",

}