# spanish.py

TRANSLATIONS = {
    # Diálogo Principal
    "Adicionar Cards com Delimitadores": "Añadir Tarjetas con Delimitadores",
    "Idioma:": "Idioma:",
    "Pronto": "Listo",
    "Cards: {}": "Tarjetas: {}",
    "Adicionar Imagem, Som ou Vídeo": "Añadir Imagen, Sonido o Vídeo",
    "Gerenciar Mídia": "Gestionar Archivos",
    "Exportar para HTML": "Exportar a HTML",
    "Exportar cards para arquivo HTML": "Exportar tarjetas a un archivo HTML",
    "Visualizar Cards": "Visualizar Tarjetas",
    "Mostrar": "Mostrar",
    "Mostra todos os cards do deck em 'Digite seus cards'": "Muestra todas las tarjetas del mazo en 'Introduce tus tarjetas'",
    "Editar": "Editar",
    "Parar Edição": "Detener Edición",
    "Ativa/desativa a edição em tempo real dos cards mostrados.": "Activa/desactiva la edición en tiempo real de las tarjetas mostradas.",
    "Digite seus cards:": "Introduce tus tarjetas:",
    "Aplicar cor ao texto": "Aplicar color al texto",
    "Aplicar cor de fundo ao texto": "Aplicar color de fondo al texto",
    "Digite seus cards aqui...": "Introduce tus tarjetas aquí...",
    "Etiquetas:": "Etiquetas:",
    "Digite as etiquetas aqui (uma linha por card)...": "Introduce las etiquetas aquí (una línea por tarjeta)...",
    "Preview:": "Vista Previa:",
    "Numerar Tags": "Numerar Etiquetas",
    "Repetir Tags": "Repetir Etiquetas",
    "Mostrar Etiquetas": "Mostrar Etiquetas",
    "Ocultar Etiquetas": "Ocultar Etiquetas",
    "Mudar Tema": "Cambiar Tema",
    "Tema Claro": "Tema Claro",
    "Tema Escuro": "Tema Oscuro",
    "📝 Editar em Grade": "📝 Editar en Cuadrícula",
    "📄 Editar como Texto": "📄 Editar como Texto",
    "Alterna entre a edição de texto livre e uma grade estilo planilha.": "Alterna entre la edición de texto libre y una cuadrícula estilo hoja de cálculo.",
    "Juntar Linhas": "Unir Líneas",
    "Juntar todas as linhas": "Unir todas las líneas",
    "Destaque": "Resaltar",
    "Destacar texto (Ctrl+M)": "Resaltar texto (Ctrl+M)",
    "B": "N",
    "Negrito (Ctrl+B)": "Negrita (Ctrl+N)",
    "I": "C",
    "Itálico (Ctrl+I)": "Cursiva (Ctrl+K)",
    "U": "S",
    "Sublinhado (Ctrl+U)": "Subrayado (Ctrl+S)",
    "Concatenar": "Concatenar",
    "Concatenar texto": "Concatenar texto",
    "Limpar Tudo": "Limpiar Todo",
    "Limpar todos os campos e configurações": "Limpiar todos los campos y configuraciones",
    "Desfazer": "Deshacer",
    "Desfazer (Ctrl+Z)": "Deshacer (Ctrl+Z)",
    "Refazer": "Rehacer",
    "Refazer (Ctrl+Y)": "Rehacer (Ctrl+Y)",
    "Pesquisar... Ctrl+P": "Buscar... Ctrl+P",
    "Pesquisar": "Buscar",
    "Substituir tudo por... Ctrl+Shift+R": "Reemplazar todo por... Ctrl+Shift+R",
    "Substituir Tudo": "Reemplazar Todo",
    "Cloze 1 (Ctrl+Shift+D)": "Cloze 1 (Ctrl+Shift+D)",
    "Adicionar Cloze 1 (Ctrl+Shift+D)": "Añadir Cloze 1 (Ctrl+Shift+D)",
    "Cloze 2 (Ctrl+Shift+F)": "Cloze 2 (Ctrl+Shift+F)",
    "Adicionar Cloze 2 (Ctrl+Shift+F)": "Añadir Cloze 2 (Ctrl+Shift+F)",
    "Remover Cloze": "Quitar Cloze",
    "Remover Cloze (sem atalho)": "Quitar Cloze (sin atajo)",
    "Decks: {}": "Mazos: {}",
    "Pesquisar decks...": "Buscar mazos...",
    "Digite o nome do novo deck...": "Introduce el nombre del nuevo mazo...",
    "Criar Deck": "Crear Mazo",
    "Excluir Deck": "Eliminar Mazo",
    "Modelos ou Tipos de Notas: {}": "Tipos de Nota: {}",
    "Pesquisar tipos de notas...": "Buscar tipos de nota...",
    "Mapeamento de Campos": "Mapeo de Campos",
    "Associe cada parte a um campo:": "Asigna cada parte a un campo:",
    "Parte {} -> Ignorar": "Parte {} -> Ignorar",
    "Parte {} -> {}": "Parte {} -> {}",
    "Midia {}": "Archivo {}",
    "Delimitadores:": "Delimitadores:",
    "Tab": "Tabulador",
    "Vírgula": "Coma",
    "Ponto e Vírgula": "Punto y Coma",
    "Dois Pontos": "Dos Puntos",
    "Interrogação": "Interrogación",
    "Barra": "Barra",
    "Exclamação": "Exclamación",
    "Pipe": "Pleca (|)",
    "Ocultar Decks/Modelos/Delimitadores": "Ocultar Mazos/Modelos/Delimitadores",
    "Mostrar Decks/Modelos/Delimitadores": "Mostrar Mazos/Modelos/Delimitadores",
    "Adicionar Cards (Ctrl+R)": "Añadir Tarjetas (Ctrl+R)",
    "Salvando...": "Guardando...",
    "Salvo": "Guardado",
    "Erro ao salvar": "Error al guardar",
    "Selecione um modelo para ver a pré-visualização.": "Selecciona un tipo de nota para ver la vista previa.",
    "Erro:": "Error:",
    "Modelo não encontrado.": "Tipo de nota no encontrado.",
    "Frente do Cartão (Preview)": "Anverso de la Tarjeta (Vista Previa)",
    "Verso do Cartão (Preview)": "Reverso de la Tarjeta (Vista Previa)",
    "Erro na pré-visualização:": "Error en la vista previa:",
    "Confirmação": "Confirmación",
    "Tem certeza de que deseja limpar tudo? Isso não pode ser desfeito.": "¿Estás seguro de que quieres borrar todo? Esta acción no se puede deshacer.",
    "Todos os campos e configurações foram limpos!": "¡Todos los campos y configuraciones han sido borrados!",
    "Selecione um deck e um modelo!": "¡Selecciona un mazo y un tipo de nota!",
    "Digite algum conteúdo!": "¡Introduce algún contenido!",
    "{} cards adicionados com sucesso!": "¡{} tarjetas añadidas correctamente!",
    "Selecione um deck primeiro!": "¡Selecciona un mazo primero!",
    "Deck '{}' não encontrado!": "¡Mazo '{}' no encontrado!",
    "Nenhum card encontrado no deck '{}'!": "¡No se encontraron tarjetas en el mazo '{}'!",
    "Erro ao salvar estado antes de 'Mostrar': {}": "Error al guardar el estado antes de 'Mostrar': {}",
    "Use a função 'Mostrar' para carregar os cards de um deck antes de editar.": "Usa la función 'Mostrar' para cargar las tarjetas de un mazo antes de editar.",
    "Modo de edição ativado.": "Modo de edición activado.",
    "Modo de edição desativado.": "Modo de edición desactivado.",
    "O número de linhas foi alterado. Modo de edição desativado para evitar erros.": "El número de líneas ha cambiado. Modo de edición desactivado para evitar errores.",
    "Atualizando card...": "Actualizando tarjeta...",
    "Card {} atualizado!": "¡Tarjeta {} actualizada!",
    "Erro ao atualizar": "Error al actualizar",
    "Nenhum estado anterior salvo encontrado!": "No se encontró ningún estado guardado anteriormente.",
    "Por favor, selecione uma célula na grade primeiro.": "Por favor, selecciona una celda en la cuadrícula primero.",
    "Selecionar Mídia": "Seleccionar Archivo",
    "🖼️ Adicionar Imagem/Mídia...": "🖼️ Añadir Imagen/Archivo...",
    "Colar HTML sem Tag e sem Formatação": "Pegar HTML sin Etiquetas ni Formato",
    "Colar com Tags HTML": "Pegar con Etiquetas HTML",
    "Colar do Excel com Ponto e Vírgula": "Pegar desde Excel con Punto y Coma",
    "Colar do Word": "Pegar desde Word",
    "Nenhuma imagem, texto ou HTML encontrado na área de transferência.": "No se encontró ninguna imagen, texto o HTML en el portapapeles.",
    "Nenhum texto encontrado na área de transferência para colar como Excel.": "No se encontró texto en el portapapeles para pegar como Excel.",
    "Nenhum texto encontrado na área de transferência para colar como Word.": "No se encontró texto en el portapapeles para pegar como Word.",
    "Nenhum texto ou HTML encontrado na área de transferência.": "No se encontró texto ni HTML en el portapapeles.",
    "Erro na Exportação": "Error de Exportación",
    "Ocorreu um erro durante a exportação: {}": "Ocurrió un error durante la exportación: {}",
    "Por favor, insira um texto para pesquisar.": "Por favor, introduce un texto para buscar.",
    "Texto '{}' não encontrado.": "Texto '{}' no encontrado.",
    "Todas as ocorrências de '{}' foram substituídas por '{}'.": "Todas las apariciones de '{}' fueron reemplazadas por '{}'.",
    "Todas as ocorrências de '{}' foram removidas.": "Todas las apariciones de '{}' fueron eliminadas.",
    "Por favor, insira um nome para o deck!": "¡Por favor, introduce un nombre para el mazo!",
    "Erro ao criar o deck: {}": "Error al crear el mazo: {}",
    "Etiquetas (Selecionado)": "Etiquetas (Seleccionado)",
    "Por favor, selecione uma palavra para adicionar o cloze.": "Por favor, selecciona una palabra para añadir el cloze.",
    "Erro ao carregar configurações: {}": "Error al cargar la configuración: {}",
    "Nenhum arquivo de mídia foi adicionado ou referenciado no texto!": "¡No se han añadido ni referenciado archivos multimedia en el texto!",
    "Selecionar Mídia para {}": "Seleccionar Archivo para {}",
    "Ocultar Ferramentas": "Ocultar Herramientas",
    "Mostrar Ferramentas": "Mostrar Herramientas",
    "Campo {}": "Campo {}",
    "Confirmar Exclusão de Deck": "Confirmar Eliminación de Mazo",
    "Você tem certeza que deseja excluir o deck '{}'?\n\nIsso excluirá permanentemente {} card(s) e suas mídias associadas (se não forem usadas em outros decks).\n\nESTA AÇÃO NÃO PODE SER DESFEITA.": "¿Estás seguro de que quieres eliminar el mazo '{}'?\n\nEsto eliminará permanentemente {} tarjeta(s) y sus archivos multimedia asociados (si no son usados por otros mazos).\n\nESTA ACCIÓN NO SE PUEDE DESHACER.",
    "Ocorreu um erro ao excluir o deck: {}": "Ocurrió un error al eliminar el mazo: {}",

    # Novos botões de ordenação
    "Ordem Alfabética": "Orden Alfabético",
    "Organizar cards em ordem alfabética (A-Z / Z-A)": "Ordenar tarjetas en orden alfabético (A-Z / Z-A)",
    "Ordem de Criação": "Orden de Creación",
    "Organizar por data de criação e mostrar/ocultar data": "Ordenar por fecha de creación y mostrar/ocultar fecha",
    "Ordem Aleatória": "Orden Aleatorio",
    "Organizar cards em ordem aleatória": "Ordenar tarjetas en orden aleatorio",
    "Mais Errados": "Más Falladas",
    "Organizar por cards mais errados (com mais lapsos)": "Ordenar por tarjetas más falladas (con más lapsos)",
    "Mais Certos": "Menos Falladas",
    "Organizar por cards mais certos (com menos lapsos)": "Ordenar por tarjetas menos falladas (con menos lapsos)",

    # Diálogo do Gerenciador de Mídia
    "Gerenciador de Mídia": "Gestor Multimedia",
    "Arquivos de Mídia Atuais": "Archivos Multimedia Actuales",
    "Renomear": "Renombrar",
    "Deletar": "Eliminar",
    "Deletar Todos": "Eliminar Todo",
    "Preview da Mídia": "Vista Previa del Archivo",
    "Renomear Arquivo": "Renombrar Archivo",
    "Novo nome:": "Nuevo nombre:",
    "Confirmar Exclusão": "Confirmar Eliminación",
    "Tem certeza de que deseja deletar o arquivo '{}'?": "¿Estás seguro de que quieres eliminar el archivo '{}'?",
    "Tem certeza de que deseja deletar TODOS os {} arquivos de mídia?": "¿Estás seguro de que quieres eliminar TODOS los {} archivos multimedia?",
    "Arquivo renomeado de '{}' para '{}'.": "Archivo renombrado de '{}' a '{}'.",
    "O nome '{}' já existe. Por favor, escolha outro nome.": "El nombre '{}' ya existe. Por favor, elige otro nombre.",
    "Erro ao renomear arquivo: {}": "Error al renombrar el archivo: {}",
    "Arquivo '{}' deletado com sucesso.": "Archivo '{}' eliminado con éxito.",
    "Erro ao deletar arquivo: {}": "Error al eliminar el archivo: {}",
    "Todos os arquivos de mídia foram deletados.": "Todos los archivos multimedia han sido eliminados.",
    "Nenhum arquivo de mídia para deletar.": "No hay archivos multimedia para eliminar.",

    # Diálogo do Visualizador de Cards
    "Visualizador de Cards": "Visualizador de Tarjetas",
    "Gerar": "Generar",
    "Copiar para Área de Transferência": "Copiar al Portapapeles",
    "Salvar como HTML": "Guardar como HTML",
    "Impressão": "Imprimir",
    "Nenhum card para visualizar.": "No hay tarjetas para visualizar.",
    "Conteúdo copiado para a área de transferência!": "¡Contenido copiado al portapapeles!",
    "Salvar Arquivo HTML": "Guardar Archivo HTML",
    "Arquivo HTML salvo em: {}": "Archivo HTML guardado en: {}",
    "Erro ao salvar arquivo: {}": "Error al guardar el archivo: {}",
    "Visualização de Impressão": "Vista Previa de Impresión",
    "Erro ao gerar preview de impressão: {}": "Error al generar la vista previa de impresión: {}",

    # Modo Iniciante
    "Modo Iniciante": "Modo Principiante",
    "Modo Completo": "Modo Completo",
    "Simplifica a interface para mostrar apenas as funções essenciais.": "Simplifica la interfaz para mostrar solo las funciones esenciales.",
    "Mostra todas as ferramentas avançadas.": "Muestra todas las herramientas avanzadas.",
    "instructions_button": "Instrucciones",
    "instructions_title": "Instrucciones (Modo Principiante)",
    "beginner_instructions_line1": "<b>1. Una tarjeta por línea.</b>",
    "beginner_instructions_line2": "<b>2. Separa el anverso del reverso con un punto y coma ( ; ).</b>",
    "beginner_instructions_example_title": "Ejemplo:",
    "beginner_instructions_example_text": "capital de España ; Madrid",
}